### ISSUE TITLE
Add ratings/catalog endpoint

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#110]
Ideally the data returned would be in the form of a list of rating templates (with their metadata) with a listing of rating specs (with their metadata) with a listing of effective dates.

The parameterized filtering could include rating template id, rating spec id, beginning effective date, and ending effective date

**Comment by rripken** [comment]
Is the proposed catalog to consist of a list of templates with each template having a list of specs and each spec having lists of effective dates?   So a list 3 levels deep?  
Going to be "interesting" to implement paging for that.

How painful would it be if there were two or three different catalogs?

Maybe the template catalog could include all the template metadata and just a list of the spec id's but not the full spec metadata.   Template catalog could filter by template id.

Then the Spec catalog would include the full spec metadata and just a list of the effective dates?  This could filter by template id and/or rating spec id.  

Is a catalog for the ratings actually needed?  Doesn't the existing rating set stuff let you filter by start/end dates?  Its been a while since I did rating set stuff I could have forgotten something important.

**Comment by MikeNeilson** [comment]
I was thinking about that in regards to other things two. e.g. do we need to nest the kitchen sink?
or is it reasonable to expect the user to query the higher level info and only query for the next lower even on ui event?

From a webui perspective the answer is absolutely yes. CWMSVue and the hec-cwms-data-access may have differing opinions.

But yes, I still think a new endpoint is needed. While the existing ratings endpoint let's you do some searches
1) it's only in the previous rather nested format
2) it's generated in the database so it would be difficult for us to fix/extend promptly.

I like you're split catalog idea, let's see how it shakes out.

**Comment by rripken** [comment]
See, I'd already forgotten about how the RatingSetDao for Radar was going through RatingSet.fromDatabase(....)

CwmsDbRatingJooq has catTemplateIds, catSpecId and catRatings - maybe part of the answer is to start at the db and see what is easy to get.

**Comment by adamkorynta** [comment]
CWMSVue uses the following query to grab the kitchen sink:

```
SELECT temp.PARAMETERS_ID,
       temp.INDEPENDENT_PARAMETERS,
       temp.DEPENDENT_PARAMETER,
       temp.RATING_METHODS,
       temp.TEMPLATE_CODE     AS TEMPLATE_TEMPLATE_CODE,
       temp.DESCRIPTION       AS TEMPLATE_DESCRIPTION,
       temp.VERSION           AS TEMPLATE_VERSION,
       temp.TEMPLATE_ID       AS TEMPLATE_TEMPLATE_ID,
       temp.OFFICE_ID         AS TEMPLATE_OFFICE_ID,
       spec.RATING_SPEC_CODE,
       spec.LOC_ALIAS_GROUP,
       spec.LOC_ALIAS_CATEGORY,
       spec.ALIASED_ITEM,
       spec.DEP_ROUNDING_SPEC,
       spec.IND_ROUNDING_SPECS,
       spec.DATE_METHODS,
       spec.AUTO_MIGRATE_EXT_FLAG,
       spec.AUTO_ACTIVATE_FLAG,
       spec.AUTO_UPDATE_FLAG,
       spec.ACTIVE_FLAG,
       spec.SOURCE_AGENCY,
       spec.LOCATION_ID,
       spec.RATING_ID,
       spec.TEMPLATE_CODE     AS SPEC_TEMPLATE_CODE,
       spec.DESCRIPTION       AS SPEC_DESCRIPTION,
       spec.VERSION           AS SPEC_VERSION,
       spec.TEMPLATE_ID       AS SPEC_TEMPLATE_ID,
       spec.OFFICE_ID         AS SPEC_OFFICE_ID,
       rat.DATABASE_UNITS,
       rat.FORMULA,
       rat.RATING_ID,
       rat.EFFECTIVE_DATE     AS RAT_EFFECTIVE_DATE,
       rat.PARENT_RATING_CODE,
       rat.RATING_CODE,
       rat.OFFICE_ID          AS RAT_OFFICE_ID,
       rat.LOCATION_ID        AS RAT_LOCATION_ID,
       rat.TEMPLATE_ID        AS RAT_TEMPLATE_ID,
       rat.VERSION            AS RAT_VERSION,
       rat.ACTIVE_FLAG        AS RAT_ACTIVE_FLAG,
       rat.DESCRIPTION        AS RAT_DESCRIPTION,
       rat.ALIASED_ITEM       AS RAT_ALIASED_ITEM,
       rat.LOC_ALIAS_CATEGORY AS RAT_LOC_ALIAS_CATEGORY,
       rat.LOC_ALIAS_GROUP    AS RAT_ALIAS_GROUP,
       rat.RATING_SPEC_CODE   AS RAT_RATING_SPEC_CODE,
       rat.TEMPLATE_CODE      AS RAT_TEMPLATE_CODE,
       rat.CREATE_DATE        AS RAT_CREATE_DATE,
       rat.TRANSITION_DATE    AS RAT_TRANSITION_DATE,
       rat.NATIVE_UNITS       AS RAT_NATIVE_UNITS
FROM CWMS_V_RATING_TEMPLATE temp
         LEFT OUTER JOIN CWMS_V_RATING_SPEC spec
                         ON spec.TEMPLATE_ID = temp.TEMPLATE_ID
         LEFT OUTER JOIN CWMS_V_RATING rat ON rat.RATING_ID = spec.RATING_IDWHERE spec.LOC_ALIAS_CATEGORY IS NULL AND rat.LOC_ALIAS_CATEGORY IS NULL
```

**Comment by MikeNeilson** [comment]
My gut feeling is don't put that kitchen sink in RADAR. but I'll except some judgement from y'all.

Don't forget to update to the newest hec-cwms-rating while you're at it though.

**Comment by adamkorynta** [comment]
To populate the rating template rows in CWMSVue, I'll need a catalog of templates which can be a separate query.

For specs, I can do it any number of ways, I don't know what the most efficient would be. One query to get all of the specs, then a follow up query to get the individual ratings for each spec? Or a single query with all specs? I don't need the actual rating table data up front, but there's metadata on each individual rating curve that is displayed in the CWMSVue table.

**Comment by rripken** [comment]
Lets start with the templates.  Is JSON or XML more important to do first?   Does it matter if the RatingTemplate serializes in the same way as the RatingTemplate embedded in the RatingSets?     I ask b/c RatingSetDao was going through RatingSet.fromDatabase and I don't think that is the way to go for these catalogs.  

Its sounds like we could use CwmsRatingJdbcDao.  If I use CwmsRatingJdbcDao I'll get back IRatingTemplate objects that are implemented with JDomRatingTemplate.  For the Swagger codegen stuff to work well I think we need Radar to make its own dto objects but it should be relatively straightforward to map IRatingTemplate -> RatingTemplateDTO.  This is similar to how the VerticalDatum stuff was done. 

I'll create an example output.

**Comment by rripken** [comment]
What do you think about this for template with specIds?

```
[  {
    "office-id": "LRL",
    "id": "Stage;Stage.USGS-CORR",
    "version": "USGS-CORR",
    "description": "Stream Stage Correction Rating",
    "dependent-parameter": "Stage",
    "independent-parameter-list": [
      "Stage"
    ],
    "specs": [
      "IN03017.Stage;Stage.USGS-CORR.USGS-NWIS",
      "Brookville.Stage;Stage.USGS-CORR.USGS-NWIS"
    ]
  },
  {
    "office-id": "LRL",
    "id": "Stage;Flow.USGS-EXSA",
    "version": "USGS-EXSA",
    "description": "Expanded, Shift-Adjusted Stream Rating",
    "dependent-parameter": "Flow",
    "independent-parameter-list": [
      "Stage"
    ],
    "specs": [
      "IN03017.Stage;Flow.USGS-EXSA.USGS-NWIS",
      "Brookville.Stage;Flow.USGS-EXSA.USGS-NWIS"
    ]
  },
  {
    "office-id": "LRL",
    "id": "Stage;Stage-Corrected.Linear",
    "version": "Linear",
    "description": "Stream Stage Correction Rating",
    "dependent-parameter": "Stage-Corrected",
    "independent-parameter-list": [
      "Stage"
    ],
    "specs": []
  }
]
```

**Comment by adamkorynta** [comment]
Right now we need the count of the referenced specs in the CWMSVue table so that mapping works great.

We also need the rating method (in range, out of range low, out of range high) for each parameter.

**Comment by rripken** [comment]
Ok. I'll map it like the xml does.   Do you need the position field or can we assume the lists are ordered?
Like this:
```
[{
    "office-id": "LRL",
    "id": "Stage;Stage.USGS-CORR",
    "version": "USGS-CORR",
    "description": "Stream Stage Correction Rating",
    "dependent-parameter": "Stage",
    "independent-parameter-specs": [
      {
        "parameter": "Stage",
        "in-range-method": "ERROR",
        "out-of-range-low-method": "LINEAR",
        "out-of-range-high-method": "ERROR"
      }
    ],
    "specs": [
      "IN03017.Stage;Stage.USGS-CORR.USGS-NWIS",
      "Brookville.Stage;Stage.USGS-CORR.USGS-NWIS"
    ]
  },
  {
    "office-id": "LRL",
    "id": "Stage;Flow.USGS-EXSA",
    "version": "USGS-EXSA",
    "description": "Expanded, Shift-Adjusted Stream Rating",
    "dependent-parameter": "Flow",
    "independent-parameter-specs": [
      {
        "parameter": "Stage",
        "in-range-method": "ERROR",
        "out-of-range-low-method": "LINEAR",
        "out-of-range-high-method": "ERROR"
      }
    ],
    "specs": [
      "IN03017.Stage;Flow.USGS-EXSA.USGS-NWIS",
      "Brookville.Stage;Flow.USGS-EXSA.USGS-NWIS"
    ]
  },
  {
    "office-id": "LRL",
    "id": "Stage;Stage-Corrected.Linear",
    "version": "Linear",
    "description": "Stream Stage Correction Rating",
    "dependent-parameter": "Stage-Corrected",
    "independent-parameter-specs": [
      {
        "parameter": "Stage",
        "in-range-method": "ERROR",
        "out-of-range-low-method": "LINEAR",
        "out-of-range-high-method": "ERROR"
      }
    ],
    "specs": []
  }
]
```

**Comment by rripken** [comment]
Is there a default for the in/out methods?  Or should I not break the field apart and just return the raw rating method String "rating-method":"NEAREST,LINEAR,NEAREST/NEAREST,LINEAR,NEAREST"

**Comment by rripken** [comment]
I guess I'm asking, do you like this any better?  

```
{
    "office-id": "LRL",
    "id": "Stage;Stage-Corrected.Linear",
    "version": "Linear",
    "description": "Stream Stage Correction Rating",
    "dependent-parameter": "Stage-Corrected",
    "independent-parameters": "Stage",
    "rating-methods":"ERROR,LINEAR,ERROR",
    "specs": []
  }
```

And it would be up to the user to appropriately split independent-parameters and rating-methods.    The RatingTemplate xml format pulls them apart and makes a list and adds child elements for each rating method

**Comment by adamkorynta** [comment]
I put together examples with multiple independent parameters and I think that makes the first example a whole lot clearer.

```
{
    "office-id": "SWT",
    "id": "Opening-Spillway_Gates,Elev,Elev-Tailwater;Flow.Standard",
    "version": "Standard",
    "description": "",
    "dependent-parameter": "Flow",
    "independent-parameter-specs": [
      {
        "parameter": "Opening-Spillway_Gates",
        "in-range-method": "ERROR",
        "out-of-range-low-method": "LINEAR",
        "out-of-range-high-method": "ERROR"
      },
      {
        "parameter": "Elev",
        "in-range-method": "ERROR",
        "out-of-range-low-method": "LINEAR",
        "out-of-range-high-method": "ERROR"
      },
      {
        "parameter": "Elev-Tailwater",
        "in-range-method": "ERROR",
        "out-of-range-low-method": "LINEAR",
        "out-of-range-high-method": "ERROR"
      }
    ],
    "specs": []
  }
```

versus what I think the second one is suggesting

```
{
    "office-id": "LRL",
    "id": "Opening-Spillway_Gates,Elev,Elev-Tailwater;Flow.Standard",
    "version": "Standard",
    "description": "",
    "dependent-parameter": "Flow",
    "independent-parameters": "Opening-Spillway_Gates,Elev,Elev-Tailwater",
    "rating-methods":"ERROR,LINEAR,ERROR,ERROR,LINEAR,ERROR,ERROR,LINEAR,ERROR",
    "specs": []
  }
```

**Comment by rripken** [comment]
I'll go with the more verbose version.

How about this for Specs?
{
    "office-id": "LRL",
    "rating-id": "Brookville.Stage;Flow.Logarithmic.USGS-NWIS",
    "template-id": "Stage;Flow.Logarithmic",
    "location-id": "Brookville",
    "version": "USGS-NWIS",
    "in-range-method": "NEAREST",
    "out-range-low-method": "LINEAR",
    "out-range-high-method": "NEAREST",
    "active": true,
    "auto-update": true,
    "auto-activate": true,
    "auto-migrate-extension": true,
    "ind-rounding-specs": [
      {
        "value": "2223456782"
      }
    ],
    "dep-rounding-spec": "2222233332",
    "description": "WHITEWATER RIVER AT BROOKVILLE, IN USGS-NWIS Stream Rating (Base + Shifts and Offsets)",
    "effective-dates": [
      "2011-10-16T04:00:00Z"
    ]
  }

**Comment by rripken** [comment]
I ended up making controllers and dao for RatingTemplate and RatingSpec.    The template contain a ratingIds field that will let you see how many there are and also link to RatingSpec.   The RatingSpec contains a list of the effectiveDates so that you can hopefully know what to query if you want a specific rating table.  #164

**Comment by rma-rripken** [comment]
I believe there is still one level of catalog/metadata/data end-point still needed.   RatingCatalogDao has a method buildFullRatingCatalog which returns NavigableMap<RatingTemplate, NavigableMap<RatingSpec, NavigableSet<AbstractRating>>>   #164 added a way to get the RatingTemplate and RatingSpec but we are still missing an end-point to return AbstractRating.   I'm not entirely sure how they would be returned to the user.   
Option 1) AbstractRating objects can serialize themselves to xml (but not json) so one option would be to only support XML for this end-point and fetch the full objects and have them serialize themselves into the response.   
Option 2) Another option would be to make new DTO objects for the various types of AbstractRating and then we could serialize them as JSONv2 the way we do with other things.   Its a little tedious - we'd have to make 5 new DTO types (TransitionalRating, ExpressionRating, TableRating, USGSStreamTableRating, VirtualRating) and then map the fields from the hec,data,cwmsData classes to our DTO types.   But that would match what we've done in basically every other place in RADAR.  It would let Radar completely control the serialization.
Option 3) Another possibility might be to create an object that represents a row in CWMS_V_RATING_TEMPLATE and then leave it to callers to map the row data into the correct AbstractRating type.   This is my least favorite solution and it sort of ignores the existence of TransitionalRating and VirtualRating which are in different tables.

Are there other solutions?

**Comment by MikeNeilson** [comment]
I can't really think of other solution but I think the primary initial user of the endpoint will be cwmsvue (well, rating editor) and that will already expect XML I think option 1 is fine. *if* there ends up being extra time, not other major issues, then we do option 2.

**Comment by adamkorynta** [comment]
If you pursue first option will end up retrieving every single rating in the database with all data, which could be very time intensive (EXSA curves are notorious). Since we only want the metadata, that's doing a bunch of extra work. I don't know what happens if you try and retrieve them using lazy loading and then try to serialize. It might work just fine, or it might try to load all the data at the time of serialization. Might be worth testing out.

**Comment by MikeNeilson** [comment]
... oy. Sounds like option 2 it is, unless testing with lazy loading is really fast.

**Comment by rma-rripken** [comment]
It doesn't look to me like AbstractRating supports the Lazy load argument directly but from looking at the code for 5 minutes it looks to me like AbstractRating.fromDatabase calls some pl/sql to get xml and then returns fromXml(xmlText).  
The pl/sql it calls is cwms_rating.retrieve_ratings_xml_data.   Thats the same method that RatingSet fromDatabase calls.  
The routine has an p_include_points parameter that RatingSet sets to 'F' when its doing Lazy loads.  Maybe we could do that call directly with p_include_points='F' and feed the result into AbstractRating and we'd have lazy versions of the Rating objects.   Maybe.

**Comment by rma-rripken** [comment]
Here is where I am now with the Ratings metadata.   

{
  "page": "fHwyMA==",
  "rating-metadata": [
    {
      "rating-spec": {
        "office-id": "SWT",
        "rating-id": "AARK.Stage;Flow.BASE.PRODUCTION",
        "template-id": "Stage;Flow.BASE",
        "location-id": "AARK",
        "version": "PRODUCTION",
        "in-range-method": "LINEAR",
        "out-range-low-method": "NEAREST",
        "out-range-high-method": "NEAREST",
        "active": true,
        "auto-update": true,
        "auto-activate": true,
        "auto-migrate-extension": true,
        "independent-rounding-specs": [
          {
            "value": "4444444444"
          }
        ],
        "dependent-rounding-spec": "4444444444",
        "description": "ARKANSAS R AT ARKANSAS CITY, KS Shift-Adjusted PRODUCTION Stream Rating"
      },
      "ratings": [
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.BASE.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2021-10-05T23:56:00Z",
          "create-date": "2021-10-05T23:56:00Z",
          "description": "USGS RATING ID: 0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.BASE.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-05-30T05:00:00Z",
          "create-date": "2017-11-17T11:30:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.BASE.PRODUCTION",
          "units-id": "ft;cfs",
          "active": false,
          "effective-date": "2017-05-29T23:00:00Z",
          "create-date": "2017-07-24T14:10:00Z",
          "description": "USGS RATING ID: 0060"
        }
      ]
    },
    {
      "rating-spec": {
        "office-id": "SWT",
        "rating-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
        "template-id": "Stage;Flow.EXSA",
        "location-id": "AARK",
        "version": "PRODUCTION",
        "source-agency": "USGS",
        "in-range-method": "LINEAR",
        "out-range-low-method": "NEAREST",
        "out-range-high-method": "NEAREST",
        "active": true,
        "auto-update": true,
        "auto-activate": true,
        "auto-migrate-extension": true,
        "independent-rounding-specs": [
          {
            "value": "2223456782"
          }
        ],
        "dependent-rounding-spec": "2222233332",
        "description": "ARKANSAS R AT ARKANSAS CITY, KS Expanded, Shift-Adjusted PRODUCTION Stream Rating"
      },
      "ratings": [
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2018-07-16T16:23:00Z",
          "create-date": "2018-08-04T10:02:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2018-05-29T18:39:00Z",
          "create-date": "2018-06-13T10:02:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2018-04-10T18:32:00Z",
          "create-date": "2018-04-19T10:02:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2018-02-27T17:40:00Z",
          "create-date": "2018-02-28T10:08:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2018-01-10T19:21:00Z",
          "create-date": "2018-01-13T10:01:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-11-13T19:10:00Z",
          "create-date": "2017-12-07T10:01:00Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-09-22T16:01:00Z",
          "create-date": "2017-10-05T10:29:44Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-05-30T17:00:00Z",
          "create-date": "2017-08-09T20:22:48Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-04-07T17:00:00Z",
          "create-date": "2017-05-10T10:04:13Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-04-07T16:55:00Z",
          "create-date": "2017-04-08T10:02:56Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2017-02-17T16:15:00Z",
          "create-date": "2017-03-09T11:09:44Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2016-12-28T06:00:00Z",
          "create-date": "2017-02-22T21:56:07Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2016-11-16T06:00:00Z",
          "create-date": "2017-02-08T11:12:23Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2016-10-17T05:00:00Z",
          "create-date": "2016-11-30T22:51:45Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2016-09-11T05:00:00Z",
          "create-date": "2016-11-04T20:20:01Z",
          "description": "0060"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2016-07-04T05:00:00Z",
          "create-date": "2016-08-18T18:40:00Z",
          "transition-date": "2016-07-01T08:00:00Z",
          "description": "0059"
        },
        {
          "rating-type": "TABLE",
          "office-id": "SWT",
          "rating-spec-id": "AARK.Stage;Flow.EXSA.PRODUCTION",
          "units-id": "ft;cfs",
          "active": true,
          "effective-date": "2016-06-14T05:00:00Z",
          "create-date": "2016-07-08T17:01:02Z",
          "description": "0058"
        }
      ]
    }
  ],
  "next-page": "U1dUfHxTdGFnZTtGbG93LkVYU0F8fEFBUksuU3RhZ2U7Rmxvdy5FWFNBLlBST0RVQ1RJT058fFNXVHx8QUFSSy5TdGFnZTtGbG93LkVYU0EuUFJPRFVDVElPTnx8MjAxNi0wNi0xNFQwNTowMDowMFpbVVRDXQ==",
  "page-size": 20
}

**Comment by adamkorynta** [comment]
That looks good.

Am I understanding correctly that `page-size` refers to the number of rating curves? Meaning there might be more curves for that last spec (`AARK.Stage;Flow.EXSA.PRODUCTION`) on the next page?

**Comment by MikeNeilson** [comment]
would it make sense to nest the effective date and description into a single array? like we did for the ts_extents?

Or would that make retrieving the actual table itself more difficult?

**Comment by rma-rripken** [comment]
Yes.  There might be more ratings for that spec on the next page.  The next page would re-include the spec and then resume the list of ratings.    I'm trying to do keyset paging as described here  https://blog.jooq.org/faster-sql-paging-with-jooq-using-the-seek-method/   I'll have a branch shortly with the new classes and Dao.  

I initially wanted to list all the effective dates in the spec (like we do from the spec controller) but b/c of the paging it doesn't work out.

I think it should be possible to remove the office-id and rating-id from the individual rating objects but then I decided that they were the main point of the controller and I probably shouldn't complicate things.   

I still need to figure out how I'm going to combine the virtual ratings and usgs ratings into these results.   It may be that the user asks for 20 per page but they actually get 20 table and 20 virtual.    Or I might have to fetch 20 of each type and then only send the user the first 20 - that probably wouldn't be that bad performance wise.

**Comment by adamkorynta** [comment]
That all makes sense to me, I like that sending 20 ratings will keep the payload mostly consistent for each call.

I had the same thought about office-id/rating-id. It seems redundant, but then removing it makes things complicated and it also makes the individual ratings unable to stand apart.
