### ISSUE TITLE
location/group endpoint throws RangeError when office id supplied

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#126]
Example cURL:

```
curl -X 'GET' \
  'http://localhost:11524/cwms-data/location/group?office=SWT' \
  -H 'accept: application/json'
```

No response returned, but `RangeError:Maximum call stack size exceeded` is shown in Swagger

Didn't see a stack trace on the server-side.

**Comment by rripken** [comment]
#129

**Comment by adamkorynta** [comment]
I'm still seeing this behavior. RangeError from wagger, retrieval is over a minute for "SWT" office id.
