### ISSUE TITLE
/timeseries/group office id parameter doesn't return groups without a shared loc ref

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#137]
looks like it's filtering on the location office instead of the group's office.

**Comment by rripken** [comment]
PR #138 should fix this issue.

**Comment by rripken** [comment]
@adamkorynta  can you remind me how you triggered this?  I need to add an integration test for the PR but I'm having a hard time setting up the ts cat/group/tsId to demonstrate this.  If I remember right you were mixing data from an office with data from CWMS office.
I just tried to setup an integration test with data from two different offices (LRL and SPK) and I couldn't get the cwms_ts.store_group to use category and groups with different offices.   
cwms_ts.assign_ts_group seems like it could handle dbOfficeId  or db_office_code_all ("CWMS").   Probably be easiest if I just try to setup my test the same way things weren't working for you.
