### ISSUE TITLE
202-accepted returned where 200-ok would be better.

### ISSUE THREAD

**Issue by rripken** [USACE/cwms-data-api#151]
The LevelsController, LocationController and RatingController are returning 202-ACCEPTED instead of 200-OK. 202 would be appropriate if we'd started the operation on a background thread but weren't going to wait.

SC_ACCEPTED should be replaced with SC_OK and any tests that look for 202 from those classes should be updated to use 200

**Comment by kuruvasatya** [comment]
Hey @MikeNeilson, I can work on this, please assign this to me :)
