### ISSUE TITLE
Default logging for RADAR is very verbose

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#159]
There are lots of logs like:
Mar 31, 2022 4:36:14 PM org.apache.catalina.authenticator.AuthenticatorBase invoke
FINE: Security checking request GET /cwms-data/timeseries
Mar 31, 2022 4:36:14 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /timeseries --> false
Mar 31, 2022 4:36:14 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /timeseries --> false
Mar 31, 2022 4:36:14 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /timeseries --> false
Mar 31, 2022 4:36:14 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /timeseries --> false
Mar 31, 2022 4:36:14 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   No applicable constraint located

I am unsure if they are helpful or telling me anything. It becomes difficult to search through the log file for meaningful error messages.

**Comment by MikeNeilson** [comment]
The default logging if running from the build environment itself is intentionally verbose as that method is only intended for development diagnosis.. 

We strive to make sure production runtime concerns are logged at info or above.

There is a logging.properties file in the build for the gradle run command, you can override it to reduce the output.

If you are running in a different environment I would recommend setting cwms.radar.level=INFO in you're local logging properties to reduce the output of RADAR itself if you need other things at fine.
