### ISSUE TITLE
TimeSeries Catalog produces duplicate entries on separate pages

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#178]
When testing RADAR client against a copy of an LRL database, I found that the time series catalog produced duplicate entires for some timeseries (example CARI2.Flow.Inst.6Hours.0.OHRFC-0hrQPF on the second and third pages of the catalog with default settings). It seems to be some issue with how the cursor is handled because if I increase the page size to encompass all of the results, I do not receive duplicates.

**Comment by MikeNeilson** [comment]
This should be fixed in #188
