### ISSUE TITLE
Remove rounding spec from time series retrieval

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#181]
While comparing CWMS data returned from JDBC vs RADAR, it was identified that the rounding spec: 5567899996 is being used to round time series data.

https://github.com/USACE/cwms-radar-api/blob/24b00f749e6e5566f92f9c598137ff14c0568605/cwms_radar_api/src/main/java/cwms/radar/data/dao/TimeSeriesDaoImpl.java#L262

**Comment by MikeNeilson** [comment]
this was done as part of #187
