### ISSUE TITLE
End point for Gate Settings

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#197]
waiting for feedback with examples and descriptions of existing interfaces.

**Comment by krowvin** [comment]
Discussion [here](https://github.com/USACE/cwms-radar-api/discussions/317)

**Comment by rma-rripken** [comment]
This is also this ticket.  At least, I think:  https://jira.hecdev.net/browse/CTO-38

**Comment by MikeNeilson** [comment]
yeah. This was opened before we put it on the contract and Charles as moved it to a discussion.

**Comment by JeremyDKellett** [comment]
Does anbody know if there is a reference ts_id associated to a gate_setting object? Previously I've implemented screens where the app will write to a hardcoded version_id TS_ID (Mount Morris-Gate 01.Opening.inst.0.0.PD Input) and also the gate_change object. It occurs to me that there may be value in having that relationship more tight? Not sure if others are doing similar though.

**Comment by MikeNeilson** [comment]
FYI, you might want to add that comment to https://github.com/USACE/cwms-data-api/discussions/317, this issue got moved to discussion to coordinate things as it's getting done under a contract now.

**Comment by rma-psmorris** [comment]
@JeremyDKellett -- There is a definition of gate opening time series established in pertinent data. It might be in REGI application-specific data (Properties or CLOB/XML). The time series is written to when gate changes/settings are created, also when read from it can generate gate changes/settings.
