### ISSUE TITLE
timeseries/recent fails with ambigously defined column

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#198]
https://cwms-data.usace.army.mil/cwms-data/timeseries/recent/all%20pz%20ts%20ids?category-id=NAE%20Data%20Dissemination&office=NAE

**Comment by krowvin** [comment]
@rma-rripken bump - Close?

**Comment by rma-rripken** [comment]
Most likely fixed.  Can't say for certain without there being more detail in this issue of what was showing up in the server log.  But I'm sure enough to close this and we can reopen if it shows up again
