### ISSUE TITLE
levels getAll endpoint level-id-mask doesn't support "*" suffix

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#210]
Example cURL:

```
curl -X 'GET' \
  'http://leary.rmanet.com:11526/cwms-data/levels?level-id-mask=lvl%2A&office=LRL&page-size=400' \
  -H 'accept: application/json;version=2'
```

Response:

```
{
  "page": "MHx8bnVsbHx8NDAw",
  "levels": [],
  "page-size": 400
}
```

I have levels with the location ID of `lvl500981`, but when I pass in `lvl*` for the level-id-mask, I do not get any results.

**Comment by rma-rripken** [comment]
Can you try making the level-id-mask lvl.* 
I haven't tried this, just suspect that the regex needs to be tweaked

**Comment by rma-rripken** [comment]
Actually I was stupidly changing the column to upper before feeding to to the regex.  There is a way to make oracle do case insensitive regex but I haven't found how to do that via jooq. Including fix in #208

**Comment by adamkorynta** [comment]
I believe the PL/SQL usually uppers both the column and the input mask

**Comment by MikeNeilson** [comment]
That's what i've been doing upper on both column and input (not to say we rememverred that everywhere.) Though if the regex can be set to case insensitive cleanly that probably would be better.

**Comment by rma-rripken** [comment]
Cool.  I found a decent way to do the [case insensitive regex](https://stackoverflow.com/questions/44962787/case-insensitive-regex-with-postgres-and-jooq/44965037#44965037).    I put a similar method adapted for Oracle in JooqDao

**Comment by rma-rripken** [comment]
This seems to work.  I believe PR #208 Fixed it.    I think your regex may need to be lvl.* when I try lvl* I see some unexpected matches in with the results. And I needed to specify a start data that was a ways back.  The start/end behavior may need to be revisited.
