### ISSUE TITLE
Ratings getAll endpoint doesn't return ratings

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#212]
I've tried various combinations of input parameters, using start time of year 1799 to end time in year 2899 to get all ratings. I've even tried using exact dates and exact rating ids.

Example cURL:
```
curl -X 'GET' \
  'http://leary.rmanet.com:11526/cwms-data/ratings?at=1799-08-23T20%3A35%3A12Z&end=2899-08-23T20%3A35%3A12Z' \
  -H 'accept: */*'
```

Response:

```
{
  "ratings-catalog": {
    "query-info": {
      "time-of-query": "2022-08-24T20:35:36Z",
      "process-query": "PT0.011S",
      "format-output": "PT0.000S",
      "requested-format": "JSON",
      "requested-office": "*",
      "requested-start-time": "1799-08-23T20:35:12Z",
      "requested-end-time": "2899-08-23T20:35:12Z",
      "total-specifications-cataloged": 0,
      "unique-specifications-cataloged": 0
    },
    "comment": "Catalog of ratings that are effective at some point between 1799-08-23T20:35:12Z and 2899-08-23T20:35:12Z",
    "ratings": []
  }
}
```

**Comment by rma-rripken** [comment]
That url points at RatingController getAll.   RatingController wasn't modified when the Rating Template and Rating Spec controllers were added.  Its still the old-style pass-thru to CWMS_RATING_PACKAGE.call_RETRIEVE_RATINGS_F.     The controller returns whatever the pl/sql returns.

**Comment by rma-rripken** [comment]
Mike, I think I need a suggested plan of attack on this one.  Does someone look into fixing whatever is wrong in the pl/slq?  Is something wrong in the pl/sql or are we just using it wrong?  Should a JSONv2 endpoint be created in Radar that does all the querying itself?  Or is there a getAll style call implemented somewhere else that we can forward to?

**Comment by MikeNeilson** [comment]
Honestly, if it's the PL/SQL we'd need @perrymanmd to look at at it and it'd likely take a while to get the fix in place everywhere (well, if staged correctly through the database build process.)

If it's not excessive work I'm inclined to say create finally add the JSONv2 support so we can eventually remove that PL/SQL. 
Or analyze and find a workaround for now. 

The new format is probably the best choice, but not sure if you have the money left to work on it.
