### ISSUE TITLE
Put link to yaml schema on swagger ui landing page.

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#229]
The default swagger landing page (e.g.  https://cwms-data.usace.army.mil/cwms-data/swagger-ui.html ) Has a link to swagger-docs which is a json version of the schema.    For codegen a yaml version of the schema is needed.   
https://editor.swagger.io/  can convert the json to yaml.   But swagger ui will return a yaml version natively.  Its at 
https://cwms-data.usace.army.mil/cwms-data/swagger-config.yaml

Perhaps we can override one of the html files in the webjar and include an obvious link to the yaml version.

**Comment by MikeNeilson** [comment]
We can just add another link to the index page. it's not generated in any special way.

**Comment by rma-rripken** [comment]
Nice.  The Spring version of swagger packaged the web resources in a web jar. I was just expecting these to be packaged the same way.  

However I just noticed that the swagger-config.yaml isn't being generated - it looks like that is just a file that you or Daniel dropped in that location.  We should either get the build to update that file automatically or delete it.  It doesn't match the current implementation.  May need to research what it takes to get yaml out of swagger directly.  Maybe its just adding the right accept headers to the doc request?

**Comment by MikeNeilson** [comment]
oh, hmm. I edited that file manually to get the swagger interface to even load. If we need it to have additional information we'll have to figure out how to generate it as part of the build.

**Comment by rma-rripken** [comment]
hmm curious.  As I understand it that yaml file is just the swagger schema but in a different format.  The version its serving up is out of date - if its needed for some reason I'm surprised that have an old version doesn't cause trouble.  Perhaps it can get sorted out when the next round of radar/cwms_aaa work gets done.
