### ISSUE TITLE
Can't try legacy timeseries formats from SwaggerUI

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#237]
The timeseries end-point has a format arg and also makes us of accept-header.   The current implementation only pays attention to the format arg if there isn't an accept-header specified.   If both are specified its treated as an error.   That is fine except the swagger ui doesn't allow users to issue requests without an accept-header.  You can do it from a command line with wget or curl but the swagger-ui has a combo box for the accept header and something in the box is always selected.

It appears we can add a blank accept type to the swagger annotations and swagger will allow users to select it in the ui.  That seems like it woudl trigger a request without an accept-header.  In reality it seems to issue \*/\*.  I'd previously changed the code that triggered an error when format args and accept headers were specified to treat \*/\* as if it was empty so I think this will work.

Also.  It appears that the TimeSeries controller claims to return XML when I think its supposed to return XMLv2.

We should also better document the format arg and its relation to the accept-header so that its clearer to users how to get the format they desire.

**Comment by MikeNeilson** [comment]
That sounds reasonable. and I noticed the XML return type previous... I think have have a branch lingering with a fix actually.
