### ISSUE TITLE
Add data entry date to timeseries catalog

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#239]
For CWMSVue, there is a data entry date column for the timeseries column. For our JDBC implementation, we return the list of extents along with the data entry date for the corresponding version of the timseries. It doesn't seem to make sense to add an extra endpoint just for the data entry date. It makes sense to add it along with the extents in the timeseries catalog request.

For example:
```
 {
      "office": "LRL",
      "name": "Alpine.Stage.Inst.1Hour.0.LRGS-raw",
      "units": "m",
      "interval": "1Hour",
      "interval-offset": 0,
      "time-zone": "UTC",
      "extents": [
        {
          "earliest-time": "2015-01-01T00:00:00Z",
          "latest-time": "2017-12-15T23:00:00Z",
          "data-entry-time": "2017-12-15T23:00:00Z"
        }
      ]
    },
```

**Comment by MikeNeilson** [comment]
Hmm. hadn't though of that. 90% of the time one doesn't care, but when you do you do.

For the catalog I don't see an issue adding the element as shown, but for a given time series itself, would have to be returned with each value.

**Comment by adamkorynta** [comment]
We are not carrying around the data entry date for the time series itself, but that might be useful to turn on with a flag in the future when a use case arises.

**Comment by rma-rripken** [comment]
Does the needed data correspond to a column in AV_TS_EXTENTS_UTC?  I guess I could go find the jdbc in bitbucket.   Is it this class?  https://bitbucket.hecdev.net/projects/CWMS/repos/hec-cwms-data-access/browse/hec-db-jdbc/src/main/java/wcds/dbi/oracle/cwms/CwmsCatalogJdbcDao.java

**Comment by adamkorynta** [comment]
It's this class actually: https://bitbucket.hecdev.net/projects/CWMS/repos/hec-cwms-data-access/browse/cwms-db-jooq/src/main/java/usace/cwms/db/jooq/dao/CwmsDbTsJooq.java#1861

but yes it's from that view `AV_TS_EXTENTS_UTC.LAST_UPDATE`
