### ISSUE TITLE
catalog/timeseries cursor issue

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#243]
When comparing the rows returned by the JDBC timeseries catalog and the RADAR timeseries catalog for the SWT database. We noticed that the RADAR catalog gets cut off after a certain point. The next-page cursor is returning null, but there is still more data.

I've added two documents showing the difference.

[jdbc_swt.txt](https://github.com/USACE/cwms-radar-api/files/9789121/jdbc_swt.txt)
[leary_swt.txt](https://github.com/USACE/cwms-radar-api/files/9789122/leary_swt.txt)

For reference our page size is set to 1,000 and the only filter we are using is the "SWT" office.

**Comment by MikeNeilson** [comment]
Is is against cwms-data.usace.army.mil or a local instance?

**Comment by adamkorynta** [comment]
Local instance off of the latest in the main branch.

**Comment by adamkorynta** [comment]
I'm seeing the same issue with the location's catalog. I never get a next page cursor

**Comment by MikeNeilson** [comment]
ugh. didn't we deal with something similar barely 2 months ago?

**Comment by adamkorynta** [comment]
Sounds remarkably similar to: https://github.com/USACE/cwms-radar-api/issues/186

**Comment by MikeNeilson** [comment]
well, apparently I need to go through that again with the office id specified.... ugh. Too many broken things.

**Comment by adamkorynta** [comment]
Fixed along with: https://github.com/USACE/cwms-data-api/issues/186
