### ISSUE TITLE
Add endpoint providing the Major.Minor version of RADAR

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#248]
This will allow clients to enable/disable features that are not supported by instance of RADAR.

**Comment by MikeNeilson** [comment]
We also want this for some performance checks that are in the works in a separate repo.

**Comment by rma-rripken** [comment]
We have a version string.  Its in the info section of the schema.  We just haven't been incrementing it.

**Comment by rma-rripken** [comment]
#250

**Comment by MikeNeilson** [comment]
oh, good point, that actually should just match the gradle version number.

**Comment by rma-rripken** [comment]
It would be nice to be able to version each end-point.  
I don't see a place in the schema to do that.  There are tags, We could tag them with their version but that doesn't seem right.

**Comment by MikeNeilson** [comment]
Yeah that would get a bit much.

**Comment by adamkorynta** [comment]
Seems less useful than overall version number and would only be handy during simultaneous client+server development.
