### ISSUE TITLE
/locations and /levels POST endpoints have redundant office id parameter

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#283]
The JSON data objects already provide the office ID, adding a query parameter is redundant (and I'm not sure the expected behavior if they differ)

**Comment by MikeNeilson** [comment]
That's been gnawing at me as well. but I can't think of a reason to have both, and I think it makes more sense that the body is responsible. And thus the end point POST/PATCH/PUT should just error out if the office isn't present.

**Comment by rma-rripken** [comment]
This was already fixed in Locations and Levels.
