### ISSUE TITLE
Add capability to delete time series time window

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#303]
Currently the CWMS client uses the following parameters:

- time series id
- start time
- end time
- override protection
- start time inclusive
- end time inclusive
- version date
- max version
- office id

**Comment by rma-rripken** [comment]
Do you envision those as optional queryParameters to the existing timeseries controller delete?

**Comment by MikeNeilson** [comment]
That seems reasonable to me.

**Comment by adamkorynta** [comment]
The "start-time" and "end-time" parameter names are inconsistent with the "begin" and "end" parameters in the GET request.

**Comment by adamkorynta** [comment]
The override protection is a String instead of a boolean

**Comment by adamkorynta** [comment]
'ts_item_mask' doesn't follow the dash delimiter style. It is also called a "cookie" in the docs and I'm not sure what that means. Should probably avoid that term for confusion with HTTP cookie.

**Comment by adamkorynta** [comment]
I'm actually confused what is the `ts_item_mask` ? The time series id is already a required endpoint parameter, so I'm not sure what a ts mask would do. Oh, and it is an integer.

**Comment by adamkorynta** [comment]
The start-time/end-time docs say " or default time zone" and doesn't have the formatting examples like the other time fields. The default time zone will use the zone in the ISO 8601 string? or is default something else?

**Comment by adamkorynta** [comment]
Override protection docs don't specify what the default behavior is if not provided. Personally, I'd rather not have an "E" option and just let the default behavior error when deleting protected values.

**Comment by rma-rripken** [comment]
All great points.  #325

**Comment by adamkorynta** [comment]
All my client tests are now passing for this feature. I think it is good to close.
