### ISSUE TITLE
Catalog-TIMESERIES query is returning duplicate entries

### ISSUE THREAD

**Issue by KevinSmith-RMA** [USACE/cwms-data-api#319]
Catalog-TIMESERIES query is returning duplicate entries.

Request url:
https://cwms-data.usace.army.mil/cwms-data/catalog/TIMESERIES?page-size=1000&office=LRN

Shows a total of 5380 
Row count is actually 7683

Some duplicates include the following:

CumbR StonesR.Stage.Inst.15Minutes.0.GOES-Rev
DBLT1-BigRockCr-nrDoubleBridgesTN.Flow.Inst.15Minutes.0.dcp-rev
DERT1-DeRossettTN.Precip-Bucket.Inst.15Minutes.0.dcp-raw	 	

Should the catalog-TIMESERIES request filter out duplicate entries?

**Comment by rma-rripken** [comment]
If I make that request with a page-size of 8000 I get back 5380 entry objects.
This next part I'm doing in notepad++ so there might be something wrong with it but... If I select just the tsIds, switch them to upper-case, sort them and then remove duplicated lines I end up with 5380 lines.  So it seems like it isn't duplicating or I'm doing things differently or its duplicating when multiple pages are involved.

**Comment by MikeNeilson** [comment]
well, there's no way to "filter" the duplicates, but I'm not entirely sure why they'd be there.

**Comment by rma-rripken** [comment]
I hacked together some code to fetch all the ids returned.
When the page-size is 500 it reports 5380 in the "total" field but then I get 17 pages of data back with a total of 8200 entries.
Putting all the names in a set I end up with 5288 unique ids.
If I make the page-size 1000 I still get the 5380 "total" but then 9 pages of data with a total of 8684 entries and 5349 unique ids.
If I make the page-size 2000 I still get the 5380 "total" but then 4 pages of data with a total of 7548 entries and 5379 unique ids.
If I make the page-size 3000 I still get the 5380 "total" but then 2 pages of data with a total of 5807 entries and 5380 unique ids.

**Comment by rma-rripken** [comment]
```
 @Test
    public void timeseries_catalog_returns_unique_ids() throws Exception {
        int pageCount = 0;
        int pageSize = 3000;
        List<List<String>>  namesPerPage = new ArrayList<>();

        Response response = given().accept(Formats.JSONV2)
                .queryParam("page-size", pageSize)
                .queryParam("office", "LRN")
                .get("https://cwms-data.usace.army.mil/cwms-data/catalog/TIMESERIES")
                .then()
                .assertThat()
                .statusCode(is(200))

                .extract().response();
        pageCount++;
        System.out.println("got page:" + pageCount);


        JsonPath jsonPath = response.jsonPath();
        String total = jsonPath.getString("total");
        String nextPage = jsonPath.getString("next-page");
        System.out.println("total: " + total);

        List<String> names = jsonPath.getList("entries.name", String.class);
        namesPerPage.add(names);

        while (nextPage != null){
            response = given().accept(Formats.JSONV2)
                    .queryParam("page-size", pageSize)
                    .queryParam("office", "LRN")
                    .queryParam("page", nextPage)
                    .get("https://cwms-data.usace.army.mil/cwms-data/catalog/TIMESERIES")
                    .then()
                    .assertThat()
                    .statusCode(is(200))
                    .extract().response();
            pageCount++;
            System.out.println("got page:" + pageCount + " " + nextPage);


            jsonPath = response.jsonPath();
            nextPage = jsonPath.getString("next-page");

            names = jsonPath.getList("entries.name", String.class);
            namesPerPage.add(names);
        }

        System.out.println("got them all");

        List<String> singleList =
                namesPerPage.stream().flatMap(List::stream).collect(Collectors.toList());

        System.out.println("flattened size:" + singleList.size());

        Set<String> map = new LinkedHashSet<>(singleList);
        System.out.println("unique size:" + map.size());
        
    }
```

**Comment by rma-rripken** [comment]
So it seems to be duplicating some entries and skipping others when it does its paging

**Comment by rma-rripken** [comment]
There are parts of the catalog query I don't fully understand but I found two places where it was doing the wrong thing.  The condition that was setting the start of each page was comparing cwms_ts_id.upper gt cursor - which is sensible - but then the limit table was ordering by cwms_ts_id without the upper call.  I believe that allowed some ids to slip by when the cursor was in-between where the ids sort to when sorted normally vs sorted by upper.  Also the ts_id to use as the next page cursor gets built from the last returned result so in addition to sorting the limit portion of the query we have to sort the final results too so that the cursor is found correctly.

**Comment by MikeNeilson** [comment]
That would do it. Lexigraphical sorting means Upper case characters first and our location names are all over the place in that regard.

**Comment by FHanbali** [comment]
@MikeNeilson we're still seeing this issue returning duplicate entries using the CWMS3.3.0 release build.  Can you double check please whether or not a fix was done for this?

**Comment by adamkorynta** [comment]
@FHanbali - The attached PR was made in March 2023, while the last release of CDA was made in December 22

**Comment by MikeNeilson** [comment]
We'll be doing a release this week. We finally fixed a few really obnoxious bugs last week. But after that yeah, we need to come up with a better release cadence. Until now it was really only used by a handful of people so that's definitely becoming more critical.
