### ISSUE TITLE
Investigate why latest develop branch requires latest master branch to launch

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#322]
Running the ./gradlew run task looks like it will launch the CDA server along with the Swagger page, but returns a 404 error `The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.` when trying to access with the following in the log:

```
Tomcat listening at http://localhost:7000/

Feb 28, 2023 2:04:03 PM [org.apache.catalina.authenticator.AuthenticatorBase](https://org.apache.catalina.authenticator.authenticatorbase/) invoke

FINE: Security checking request GET /swt-data/swagger-ui.html

Feb 28, 2023 2:04:03 PM [org.apache.catalina.realm.RealmBase](https://org.apache.catalina.realm.realmbase/) findSecurityConstraints

FINE: No applicable constraints defined

Feb 28, 2023 2:04:03 PM [org.apache.catalina.authenticator.jaspic.AuthConfigFactoryImpl](https://org.apache.catalina.authenticator.jaspic.authconfigfactoryimpl/) loadPersistentRegistrations

FINE: Loading persistent provider registrations from [J:\Workspaces\git\cwms-radar-api\cwms_radar_api\build\tomcat\conf\jaspic-providers.xml]

Feb 28, 2023 2:04:03 PM [org.apache.catalina.authenticator.AuthenticatorBase](https://org.apache.catalina.authenticator.authenticatorbase/) invoke

FINE: Not subject to any constraint
```

The updates to authentication theoretically should allow the read access to still work.

**Comment by adamkorynta** [comment]
Couple of things I've noticed: the cwms_radar_api/src/main/webapp/WEB-INF/web.xml file looks to have a bad merge resolve

Additionally, swagger comes up just fine at commit hash f125cd, but then fails by commit f50e7d. I wasn't able to get commits in between to compile due to compiler errors, but I didn't check them all.

**Comment by rma-rripken** [comment]
That merge conflict has been there a while too.  Weird.  Looks like @MikeNeilson almost had it commented out.  Guess we need to run against a real tomcat once and a while.

**Comment by rma-rripken** [comment]
I made #323 to remove the bad merge resolve.

**Comment by adamkorynta** [comment]
Looks fixed from tomcat war deploy as well as the gradle run task
