### ISSUE TITLE
Support For Versioned Timeseries read.

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#346]
This will allow for retrieval of versioned time series.

**Comment by MikeNeilson** [comment]
It may be a bit more involved than that.

**Comment by adamkorynta** [comment]
I didn't see an existing ticket for version reads. I'm also not entirely convinced that this blocks the "write" task order, but I tagged it anyways as the version record will show up in CWMSVue, but the retrieval will always just grab the latest....

**Comment by rma-rripken** [comment]
This was completed by recent changes - right?

**Comment by MikeNeilson** [comment]
yeah.
