### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by anurag186** [USACE/cwms-data-api#347]
Service seems to be working from Swagger, but giving 504 Gateway Time-out error when requesting from the web browser, Postman, or from a custom java code. It was working about two days ago, so don't think it's related to network or authentication issues. Could it be that any recent changes in the code causing these issues? 

![image](https://user-images.githubusercontent.com/38192313/228868677-e79cf171-f385-4ce7-ab40-b862e0bfc395.png)
![image](https://user-images.githubusercontent.com/38192313/228868785-8456fc37-af1e-4ab9-8d13-fae0b0d78907.png)

**Comment by rma-rripken** [comment]
Making a request to the url with the browser will not add the header "accept: application/json;version=2".   If that header is not detected the service attempts to maintain backwards compatibility by calling into older pl/sql methods to retrieve and format the timeseries output.   The site should work both ways.  I just wanted to point out that those two screenshots are not the same thing.     At the moment there isn't a way to specify that you want the version=2 format and behavior via only the url.  Currently the client must be configured to also send the extra header.  There has been talk of adding a JSONv2 option to the format arg query parameter but it hasn't been done yet.

**Comment by MikeNeilson** [comment]
I believe we've added the support in the query param, but haven't create a release to push the change yet.

That said, if you are getting gateway timeouts, we are required to cut connections at 10 seconds, which which why the newer formats use pagination. You may be able to get it working again by shortening the request time frame. 

(Your particular request isn't crazy, we're just still having some configuration problems.)

**Comment by anurag186** [comment]
Thanks for the response! Passing additional header with application version seems to work for now. I will use that as a temporary fix. Hopefully this won't be required with future updates.
