### ISSUE TITLE
JooqDao changes removed exception wrapping

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#350]
It looks like changes to JooqDao.getDslContext method removed the single exit point and added an early return that does not add the ExecuteListener.  That listener must be present if we want sql exceptions automatically wrapped as NotFound, NullArgument, AlreadyExists etc. 

ApiServlet has handlers for specific exceptions that makes sure NotFound exception returns code 404. etc.   I'm not sure if Javalin exception handlers can throw additional exceptions.  If so we might be able to move the exception wrapping code out of the jooq listener and into a javalin exception handler.  Or do both - belt and suspenders.

Failing to get those exceptions wrapped means that certain end-points started returning 500 instead of 404.  
cwms-data/timeseries?name=... for example.   The radar client code was coded to handle 404 differently than 500.  So things that internally use the client code stopped working the way they previously were working.

**Comment by rma-rripken** [comment]
This line: 
https://github.com/USACE/cwms-radar-api/blob/05e6ddc2a03bc924a036d5ba941fc2e328cd76e5/cwms_radar_api/src/main/java/cwms/radar/data/dao/JooqDao.java#L45

**Comment by MikeNeilson** [comment]
yeah, looks like those should always assign to retval.
