### ISSUE TITLE
Implement delete for RatingTemplate and RatingSpec 

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#365]
CwmsRadarRatingDao in hec-db-radar does not implement deleteRatingCurve, deleteRatingTemplate and only part of deleteRatingSpecification because Radar does not have the needed delete implementations.  

Implement the delete methods such that CwmsRadarRatingDao can call into Radar. 

I don't see a tag for it, but the delete methods in CwmsRadarRatingDao are needed by RADARAPI so this issue blocks the CDA write support for scripting task.

**Comment by adamkorynta** [comment]
I have these two tickets covering templates and specs:

https://github.com/USACE/cwms-radar-api/issues/275
https://github.com/USACE/cwms-radar-api/issues/276

**Comment by rma-rripken** [comment]
#275 and #276 cover my needs.  Thanks Adam!
