### ISSUE TITLE
Actually migrate everything to kebab case

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#387]
Since it's just the new json/xml generated in Java, I think we should be okay with a breaking change here. There are already APIs that wrap this one and it's not incredibly difficult for those to be updated.

**Comment by rma-rripken** [comment]
can the needed changes be enumerated here?

**Comment by MikeNeilson** [comment]
That sounds like a royal pain. Plus I think we might have done it already.

**Comment by MikeNeilson** [comment]
I'll try to carve out some time to check though.

**Comment by adamkorynta** [comment]
Closing - can create new issues for specific endpoints that are not kebab
