### ISSUE TITLE
Non-crud endpoints not grouped as expected in Swagger (recent time series and levels as time series)

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#404]
![](https://user-images.githubusercontent.com/47677856/244824005-aa391dce-5ed2-479a-acdf-8d27d746432b.png)
The required OpenAPI annotations seem to be present for both, but they are still being added to the "Default" grouping in Swagger.

**Comment by MikeNeilson** [comment]
I'll have to look at the code for both javalin and hours. I know javalin broke OpenAPI into a separate plugin as part of the 5.x series to fix issues like that, but 5.x is java 11 only so we're stuck waiting a bit if that's where it's fixed.

**Comment by MikeNeilson** [comment]
But it's cosmetic, not functional so I don't think we should focus on it right now.
