### ISSUE TITLE
Ability to query by "bounding office"

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#427]
CWMS Locations have a concept of an "owning or database source" office and a bounding office. The bounding office is for the district boundary that a given station actually resides in.

Some districts already require this as all the data is under a division ID, additionally as we centralize some locations will be "owned" by CWMS.

Where relevant we'll need to allow searching by the bounding office instead of the normal office field.

**Comment by Usac19Bell** [comment]
As I mentioned in the recent CWBI Cloud with our NWDP RWCDS group, it would be nice to be able to search for and select two or three "bounding office" selection in the GUI.  We have some data that have kind of an 'owning' office and a 'managing' office that happen to be two different Districts and/or Division.  If we are moving every District into the same database, it would be nice to have the ability to isolate data for a single District or several Districts.  -R. Brian Bell

**Comment by rma-rripken** [comment]
Is the request to add a bounding-office filter to just the Locations Controller?  That seems easy and straight-forward.       

Or is the request to add bounding-office filters in a;; the places with data related to Locations such as location, timeseries, ratings, levels, pools, location-groups etc.    That seems significantly harder.

**Comment by rma-rripken** [comment]
I assume this filter would need to apply to the CatalogController when the DATASET is LOCATIONS.   
It looks like the LocationsController getAll does not have JSONv2 support but it was added to getOne.  It probably wouldn't be very difficult to add to getAll. The other formats supported by LocationsController are largely pass-thru to pl/sql and I wouldn't change those.

**Comment by MikeNeilson** [comment]
I would suspect eventually all, but starting with LocationController and the catalog/locations should get us like 90% of the way for most usages.

**Comment by rma-rripken** [comment]
In testing the new filter I noticed that when a bounding office filter is supplied that Locations with a null bounding-office are not returned in the result.  I think this is the correct behavior but just a heads-up.  If no bounding office filter is supplied they will be returned given that they match the other filters.  
I suspect that there isn't a way to write a bounding-office regex that matches against missing values.  

I also noticed that the Location catalog entries returned a weird "cursor" field.   That was just from a method missing @JsonIgnore.

**Comment by MikeNeilson** [comment]
That makes sense to me as far as behavior goes. but we should put a note of that in the description of the field something like "Locations will no bounding office set will not be present in results."

**Comment by MikeNeilson** [comment]
FYI For doing the search by bounding office on the timeseries catalog would involve doing a query on Locations first to narrow the space, with a `with` clause (there's already one in there I believe), who's results would be used to pull in the remaining data.

Though having just looked at the code, easier said than done. Maybe a join on locations, but definitely a bit more work than locations catalog.

**Comment by rma-rripken** [comment]
Yes, adding to the Timeseries Catalog query is more complicated.  I'm hesitant to do that at the moment b/c its probably more work than I initially estimated.

**Comment by MikeNeilson** [comment]
I'll open a new issue and take a stab at it later. I'm pretty sure it'll be relatively straight forward; for as much as one can consider joins and with clauses in SQL straight forward.
