### ISSUE TITLE
catalog/locations endpoint paging is suspiciously slow

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#428]
With out test SWT database instance, I am seeing ~90 seconds per page retrieval regardless of page sizing. I am suspicious that this means we are not paging correctly and are somehow querying the entire catalog in each page.

**Comment by MikeNeilson** [comment]
It's possible. But it could just be the planner going wrong. Which would me either the query needs to get changed or some extra indexes or hints added.

But given other reported timing issues I suspect it's just the view itself and it's getting worked on.

**Comment by rma-rripken** [comment]
In working on #427 I found that the Locations catalog query wasn't quite right.  I think that after the first page of results it wasn't adding the various filters back onto the select query for all the other pages.    Its possibly still very slow but if I got the changes right I suspect it will be a little bit better.

**Comment by rma-rripken** [comment]
That this hasn't come up again suggests to me that the mentioned changes did fix the issue
