### ISSUE TITLE
From CDA get a list of USGS Station Numbers from the group Agency Aliases

### ISSUE THREAD

**Issue by ArthurArmour** [USACE/cwms-data-api#454]
I am trying to get the USGS Station Number out of CWMS via CDA and just not quite getting it.

Here is what I have from Swagger:
![Agency_Aliases_USGS_no](https://github.com/USACE/cwms-data-api/assets/84102985/7309c735-9273-4ab4-815f-473d7a12fcbf)

I was trying to use the location/group/{group-id} to narrow it down to just the USGS Station Numbers, but was unsuccessful.
![Agency_Aliases_USGS_no_Group-ID](https://github.com/USACE/cwms-data-api/assets/84102985/c8185c0c-5762-442c-922a-7c22ef73b50c)

Do you know how I could get output from CDA that would just have the USGS Station Numbers?

Cheers,  Art

**Comment by rma-rripken** [comment]
What you are doing looks right to me.  I noticed that cwms-data had an error but our in-house CDA didn't.  Making me think that maybe this has been fixed and your CDA server doesn't have it?

**Comment by rma-rripken** [comment]
![image](https://github.com/USACE/cwms-data-api/assets/89810919/212cb22a-bd13-4ac1-9604-c989c74b3c1d)

**Comment by rma-rripken** [comment]
What do you have in the grey circle thing?

**Comment by rma-rripken** [comment]
CENWP is the group you want ?   Right?  And that is a CWMS owned group -right?  The CENWP isn't in your screenshot but I'm assuming that part is right.

**Comment by ArthurArmour** [comment]
Ryan,

I do not actually know.
I am trying to figure out if the location/group/{group-id} GET call will provide me the specificity to get me this:
***@***.***

It is confusing  because there are two office-id values (CWMS and CWMS) and then there is two id values (USGS Station Number and Agency Aliases).
So in the GET call for location/group/{group-id} I am not sure what the group-id is (maybe one of the id values above) and the office value (maybe one of the office-id values above) and then there is the category-id and I do not see category-id above.
So looking for guidance on what I put in these three text boxes below:
***@***.***

In order to get just a listing of USGS Station Number Agency Aliases.

Cheers,  Art

From: rma-rripken ***@***.***>
Sent: Monday, November 6, 2023 2:00 PM
To: USACE/cwms-data-api ***@***.***>
Cc: Armour, Arthur D CIV USARMY CENWP (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cwms-data-api] From CDA get a list of USGS Station Numbers from the group Agency Aliases (Issue #454)


CENWP is the group you want ? Right? And that is a CWMS owned group -right? The CENWP isn't in your screenshot but I'm assuming that part is right.

**Comment by ArthurArmour** [comment]
Ryan,

I am not sure what or where the grey circle thing is that you are referring to.

Cheers,  Art

From: rma-rripken ***@***.***>
Sent: Monday, November 6, 2023 1:58 PM
To: USACE/cwms-data-api ***@***.***>
Cc: Armour, Arthur D CIV USARMY CENWP (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cwms-data-api] From CDA get a list of USGS Station Numbers from the group Agency Aliases (Issue #454)


What do you have in the grey circle thing?

**Comment by ArthurArmour** [comment]
Ryan,

I do have either the latest or very close to the latest CDA version. I just updated it a week or so ago.

Cheers,  Art

From: rma-rripken ***@***.***>
Sent: Monday, November 6, 2023 1:57 PM
To: USACE/cwms-data-api ***@***.***>
Cc: Armour, Arthur D CIV USARMY CENWP (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cwms-data-api] From CDA get a list of USGS Station Numbers from the group Agency Aliases (Issue #454)


What you are doing looks right to me. I noticed that cwms-data had an error but our in-house CDA didn't. Making me think that maybe this has been fixed and your CDA server doesn't have it?

**Comment by rma-rripken** [comment]
This is what I was trying to ask about - just to make sure you have a newish build.  Sounds like you do
![image](https://github.com/USACE/cwms-data-api/assets/89810919/6e1b5560-e2fb-4c71-bf58-c44014c53388)

**Comment by rma-rripken** [comment]
These are the fields in the response
![image](https://github.com/USACE/cwms-data-api/assets/89810919/3d6b2de0-df33-46c5-903a-90e31897bcef)

**Comment by rma-rripken** [comment]
This is where they go in the request.   I don't remember exactly why we don't need the cat office id.   It seems like you got this all correct.   I think the issue is that something is wrong with the query on our end. 
![image](https://github.com/USACE/cwms-data-api/assets/89810919/bddb4c06-958b-4bd3-ba53-dfd4cec7a4d3)

**Comment by ArthurArmour** [comment]
Super. Thanks.

Cheers,  Art

From: rma-rripken ***@***.***>
Sent: Tuesday, November 7, 2023 9:32 AM
To: USACE/cwms-data-api ***@***.***>
Cc: Armour, Arthur D CIV USARMY CENWP (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cwms-data-api] From CDA get a list of USGS Station Numbers from the group Agency Aliases (Issue #454)


These are the fields in the response
***@***.***[Image removed by sender. image]<blockedhttps://user-images.githubusercontent.com/89810919/281129600-3d6b2de0-df33-46c5-903a-90e31897bcef.png>

**Comment by ArthurArmour** [comment]
Yep. I have 3.0 OAS3

***@***.***

Cheers,  Art

From: rma-rripken ***@***.***>
Sent: Tuesday, November 7, 2023 9:32 AM
To: USACE/cwms-data-api ***@***.***>
Cc: Armour, Arthur D CIV USARMY CENWP (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cwms-data-api] From CDA get a list of USGS Station Numbers from the group Agency Aliases (Issue #454)


This is what I was trying to ask about - just to make sure you have a newish build. Sounds like you do
***@***.***[Image removed by sender. image]<blockedhttps://user-images.githubusercontent.com/89810919/281128366-6e1b5560-e2fb-4c71-bf58-c44014c53388.png>

**Comment by ArthurArmour** [comment]
Ryan,

Peter Morris got me the values I needed and when I put them in I got the results I wanted. The results being only the CWMS Location ID along with the USGS Station Number.

Hello Art,

Isn't this what you are trying to get? I used the national cwbi site b/c I can't connect to your site.

Group Id = "USGS Station Number"
Office Id = "NWDP"
Category Id = "Agency Aliases"


curl -X 'GET' \
'https://cwms-data-test.cwbi.us/cwms-data/location/group/USGS%20Station%20Number?office=NWDP&category-id=Agency%20Aliases' \
-H 'accept: application/json'

Regards,
Peter


So I am good to go on this. The ticket can be closed.

Cheers,  Art

From: rma-rripken ***@***.***>
Sent: Tuesday, November 7, 2023 9:34 AM
To: USACE/cwms-data-api ***@***.***>
Cc: Armour, Arthur D CIV USARMY CENWP (USA) ***@***.***>; Author ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cwms-data-api] From CDA get a list of USGS Station Numbers from the group Agency Aliases (Issue #454)


This is where they go in the request. I don't remember exactly why we don't need the cat office id. It seems like you got this all correct. I think the issue is that something is wrong with the query on our end.
[Image removed by sender. image]<blockedhttps://user-images.githubusercontent.com/89810919/281129826-bddb4c06-958b-4bd3-ba53-dfd4cec7a4d3.png>
