### ISSUE TITLE
Docker-compose failing startup

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#465]
@rripken and @ktarbet were having issues getting the docker-compose to startup in their development environments. The specific errors can be added to the description or as comments.

**Comment by ktarbet** [comment]
15-Nov-2023 17:41:22.005 SEVERE [http-nio-7000-exec-1] cwms.cda.security.OpenIDAccessManager.<init> Unable to initialize realm.
data-api_1                | 	java.net.ConnectException: Connection refused (Connection refused)
data-api_1                | 		at java.net.PlainSocketImpl.socketConnect(Native Method)
data-api_1                | 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

**Comment by MikeNeilson** [comment]
hmm, that implements either a network/hostname/port problem or that the api isn't actually waiting for the database to be ready.

**Comment by ktarbet** [comment]
@MikeNeilson  Thanks for pointing me to networking.     

The instructions say:
Add `<real host ip> cwms-data.localhost auth.localhost traefik.localhost` to the /etc/hosts file

So instead of 127.0.0.1  I  used 192.168.206.134  in /etc/hosts  

192.168.206.134 is my Private IP,  and I can now see the swagger UI!

**Comment by MikeNeilson** [comment]
It would be good to figure out a way to not need to do that, but given how just utterly picky some of those services are about URLs and docker with address I'm not sure we can.

**Comment by MikeNeilson** [comment]
Perhaps a bigger font could help future users though.

**Comment by ktarbet** [comment]
I have a PR here to warn about 127.0.0.1 : https://github.com/USACE/cwms-data-api/pull/466

**Comment by ktarbet** [comment]
Closing this issue - docker compose is working for me -- below is my writeup.

https://github.com/USACE/cwms-data-api/wiki/How-to-use-Docker%E2%80%90compose-with-a-windows-Client
