### ISSUE TITLE
How do you use swagger authorization after docker-compose starts up?

### ISSUE THREAD

**Issue by ktarbet** [USACE/cwms-data-api#467]
docker-compose is helpful to get the services running.   What are the steps for authorization in the docker test environment?

I've connected to 
https://cwms-data.localhost:8444/cwms-data/swagger-ui.html

And clicked the 'Authorize' button.   There are several prompts, and one that looks promising is OpenIDConnect (OAuth2, password) 

I see example passwords in the docker-compose-README.md, but the prompt also requests client_id and client_secret.

![image](https://github.com/USACE/cwms-data-api/assets/4818531/a2d248b1-6106-4e1e-8db1-b4984c593b96)

**Comment by MikeNeilson** [comment]
there should be another one that doesn't need the client_secret. There should be one without the client_id as well but if not the ID is "cwms"; or at least it should be.

**Comment by ktarbet** [comment]
Here are the options:

* Api Key   
   value=?

*  CwmsAAACacAuth APIKey
     value=?

* OpenIDConnect (OAuth2, authorization_code) 
    client_id=?
    client_secret=?

* OpenIDConnect (OAuth2, implicit) 
   client_id

* OpenIDConnect (OAuth2, refresh_token)
  (no input) -- looks like for refreshing only

* OpenIDConnect (OAuth2, password) 
   username=?
   password=?
  client_id=?
  client_secret=?

* OpenIDConnect (OAuth2, client_credentials) 
   client_id =?
   client_secret =?

* OpenIDConnect (OAuth2, urn:ietf:params:oauth:grant-type:device_code) 
   (no inputs)

* OpenIDConnect (OAuth2, urn:openid:params:grant-type:ciba) 
  (no inputs)

If I put data into the Oracle database table at_sec_session, would the first option be practical?

**Comment by MikeNeilson** [comment]
try implicit.

**Comment by ktarbet** [comment]
Using Implict with client_id:  ```cwms```   After clicking the authorize button, a new tab opens with this url:

```
https://auth.localhost:8444/auth/realms/cwms/protocol/openid-connect/auth?response_type=token&client_id=cwms&redirect_uri=https%3A%2F%2Fcwms-data.localhost%3A8444%2Fcwms-data%2Foauth2-redirect.html&scope=offline_access%20openid%20profile%20phone%20acr%20web-origins%20address%20subjectDN%20email%20roles%20microprofile-jwt&state=TW9uIE5vdiAyMCAyMDIzIDE1OjIwOjM0IEdNVC0wODAwIChQYWNpZmljIFN0YW5kYXJkIFRpbWUp
```
Here is the image

![image](https://github.com/USACE/cwms-data-api/assets/4818531/f717fb14-7ce5-47ec-bcd3-27afc3857538)

**Comment by MikeNeilson** [comment]
well, that does mean it was the correct choice but there's still an issue with the config. in the file `compose_files/keycloak/realm.json` on like 665, it's possible that needs `https://cwms-data.localhost`

**Comment by MikeNeilson** [comment]
if that doesn't work i'll need to experiment a little tomorrow.

**Comment by ktarbet** [comment]
I get the same error with the tweak to realm.json.  Here is the error from the docker log:

```
auth_1| 2023-11-20 23:44:04,236 WARN  [org.keycloak.events] (executor-thread-0) type=LOGIN_ERROR, realmId=cwms, clientId=cwms, userId=null, ipAddress=172.18.0.1, error=invalid_redirect_uri, redirect_uri=https://cwms-data.localhost:8444/cwms-data/oauth2-redirect.html
```

**Comment by MikeNeilson** [comment]
hmm, yeah, that redirect is wrong. I'm going to have to experiment a little.

**Comment by MikeNeilson** [comment]
Okay, so it *is* (OAuth2,password) and you just leave the client_secret blank.

I still wasn't able to POST a CLOB (easiest end point to test) but it's entirely plausible that's an issue with checking the authorization header values without a ignoreCase.

**Comment by MikeNeilson** [comment]
... well, now I remember
```
String username = token.getBody().get("preferred_username",String.class);
// TODO: get roles from JWT and DB
return new DataApiPrincipal(username, new HashSet<RouteRole>());
```

I was waiting to pull all the values from the CWBI keycloak so I could go and match things like preferred username and mimic that configuration and never filled in the route roles. If you add role of "CWMS Users" to that set it will work, or at least allow writes for anything with a valid JWT, the l1hectest account wouldn't behave correctly as it's supposed to not have a role set.

As an alternatively solution to allow writes to the docker-compose instance one could just login to the generated oracle database as the CWMS_20 user and manually add an appropriate API key.

**Comment by ktarbet** [comment]
I logged into oracle as CWMS_20, and inserted data like this:

```
insert into CWMS_20.AT_SEC_SESSION values ('karl-test', 'sessionkey-for-testing', timestamp '2025-1-01 23:30:30.10');
```

How will the API know what username to use?   Is that coming from the browser/OS?

note:   This iteration there are only two Available authorizations in my docker-compose environment.  Do I want the first one?

![image](https://github.com/USACE/cwms-data-api/assets/4818531/ae20b65a-9bba-4aa3-9ed3-d6ee645146c4)

**Comment by MikeNeilson** [comment]
Each apikey is tied to a specific user. so it will look up and see the that user is 'karl-test' and set the roles according that that users's permissions.

**Comment by ktarbet** [comment]
Thanks -- here is what I did to get authorization:

```
SQL> insert into CWMS_20.AT_SEC_SESSION values ('L2HECTEST', 'sessionkey-for-testing', timestamp '2025-1-01 23:30:30.10');

1 row created.

SQL> insert into CWMS_20.AT_api_keys VALUES ('L2HECTEST', 'key001', 'sessionkey-for-testing', TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
```

The upper case in the username was important.
