### ISSUE TITLE
Add Office from TimeSeriesGroup Call 

### ISSUE THREAD

**Issue by Enovotny** [USACE/cwms-data-api#471]
add Office from AT_TS_GROUP_ASSIGNMENT to call to get Time Series Groups.  Similar to Location Group get output.

**Comment by rma-rripken** [comment]
Just to clarify.  You are asking that the office-id is included in the attributes for each of the assigned time series? 

For LocationGroups the output looks like:
[
  {
    "id": "CWMS Legacy Naming",
    "location-category": {
      "office-id": "CWMS",
      "id": "Agency Aliases",
      "description": "Location aliases for other agencies"
    },
    "office-id": "SWT",
    "description": "Alias group for legacy location IDs",
    "assigned-locations": [
      {
        "location-id": "TULA",
        "office-id": "SWT",
        "alias-id": "TULA",
        "attribute": 0
      },
      {
        "location-id": "KEYS",
        "office-id": "SWT",
        "alias-id": "KEYS",
        "attribute": 0
      },
      {
        "location-id": "POTW",
        "office-id": "SWT",
        "alias-id": "POTW"
      },
....


For TimeSeriesGroups its like:
[
  {
    "id": "Reporting",
    "time-series-category": {
      "office-id": "SWT",
      "id": "RDL_Aliases",
      "description": "RDL_Aliases"
    },
    "office-id": "SWT",
    "description": "Reporting",
    "assigned-time-series": [
      {
        "timeseries-id": "Peoria-Illinois.Flow.Inst.6Hours.0.NCRFCShef-CA",
        "ts-code": 4840018,
        "attribute": 0
      },
      {
        "timeseries-id": "Peoria-Illinois.Stage.Inst.15Minutes.0.lrgsShef-rev",
        "ts-code": 21481018,
        "alias-id": "Peoria-Illinois.Stage.Inst.Minutes.0.Reporting",
        "attribute": 0
      },...


You'd like each entry of the assigned-time-series lists to include office-id?

**Comment by Enovotny** [comment]
correct.  Just like the locations. since the office id for the group can be different than the office id for each time series within the group.
