### ISSUE TITLE
2023-12-10 to 2023-12-13 CWMS-Data-API Down

### ISSUE THREAD

**Issue by gamiller0-tva** [USACE/cwms-data-api#475]
It appears that CWMS API has been down for the last few days.  Is this something that will be resolved soon?  

SWAGGER says failed to load API definition and when I try it query it says HTTP Status 404  - Not Found.  

![image](https://github.com/USACE/cwms-data-api/assets/83587311/4049140e-3501-4461-8173-e01adb2d3462)

We use this operationally as a backup at TVA (mainly due to the many LDM issues), so would love to have it working again.

**Comment by MikeNeilson** [comment]
We're working on it.

The good news is i *think* I know what's wrong and have a fix staged.
The bad news is we're having a slight infrastructure problem and we can't properly investigate until it's fixed which we're waiting on now.

**Comment by MikeNeilson** [comment]
Oh, and thank you for opening an issue. In the future would you think to come here and see, perhaps a pinned issue, to know what the current status is?

Or would it mailing list users can subscribe to make more sense to you? Or maybe we can have something in the github discussions?

**Comment by gamiller0-tva** [comment]
Glad you all are looking into it.   I actually checked here first and didn't see it reported, which is why I opened it.  So I think either a pinned issue or a mailing list would work for us!

**Comment by MikeNeilson** [comment]
Need to reset a password. Should be done within the next 20 - 30 minutes or so.

**Comment by MikeNeilson** [comment]
And it's back up.

**Comment by MikeNeilson** [comment]
Okay, *this* time I think it's back up.

Sorry about the confusion, I think I tested the wrong URL (one of our internal test sites that was working) and didn't notice the lack of recovery. I've restarted the service and it appears, for now to be picking everything up correctly.

Also our new, future primary, instance is available at https://cwms.sec.usace.army.mil/cwms-data.

While we are planning to have the existing URL point there eventual, or redirect, that is a permanent location and should be be saved for backup.

**Comment by MikeNeilson** [comment]
NOTE: the cwms.sec is downish again, there was a slight config error that I'm waiting to see if the correction gets automatically picked up.

**Comment by gamiller0-tva** [comment]
I see it is working now, thank you!  We will save that other address as a backup.

**Comment by gamiller0-tva** [comment]
FYI . I get 403 forbidden when trying to go to https://cwms.sec.usace.army.mil/cwms-data

**Comment by MikeNeilson** [comment]
Thanks for letting me know. Look like we'll need to update the configuration.

**Comment by MikeNeilson** [comment]
Update on the cwms.sec address:
- Might fault, that hasn't been made public yet and that one won't be
- Our tentative plan is to make "water.sec.usace.army.mil" available but we're both working out some kinks can't make any changes to that system during the holidays anyways.
