### ISSUE TITLE
Length Limit on Location Names?

### ISSUE THREAD

**Issue by ktarbet** [USACE/cwms-data-api#481]
I found what appears to be a limit on the length of the location name (when trying to create a location using CDA)?
"name": "karltest987",  -- Works OK.

 "name": "karltest638385825378108700", --- gives error : 

ESC[36mdata-api_1                |ESC[0m 19-Dec-2023 19:12:39.257 INFO [http-nio-7000-exec-7] cwms.cda.ApiServlet.lambda$init$10 -6356645914520589032: Not Found.
ESC[36mdata-api_1                |ESC[0m        cwms.cda.api.errors.NotFoundException: ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ESC[36mdata-api_1                |ESC[0m                at cwms.cda.data.dao.JooqDao.buildNotFound(JooqDao.java:266)
ESC[36mdata-api_1                |ESC[0m                at cwms.cda.data.dao.JooqDao.wrapException(JooqDao.java:178)
ESC[36mdata-api_1                |ESC[0m                at cwms.cda.data.dao.JooqDao.connection(JooqDao.java:373)
ESC[36mdata-api_1                |ESC[0m                at cwms.cda.data.dao.LocationsDaoImpl.storeLocation(LocationsDaoImpl.java:192)
ESC[36mdata-api_1                |ESC[0m                at cwms.cda.api.LocationController.create(LocationController.java:281)

```
Caling POST https://cwms-data.test:8444/cwms-data/locations
with Data:
    {
      "office-id": "SPK",
      "name": "karltest638385825378108700",
      "latitude": 0,
      "longitude": 0,
      "timezone-name": "UTC",
      "location-kind": "SITE",
      "nation": "US",
      "horizontal-datum": "NAD83"
    }
```

**Comment by MikeNeilson** [comment]
There is a limit. It's part of the CWMS standard naming convention. Granted that could use a better error message.

**Comment by ktarbet** [comment]
Reading the manual I see this:
BaseLocation (24 characters)
SubLocation(32 characters)
