### ISSUE TITLE
Add deprecated Header to tab and CSV formats

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#484]
The tab and csv formats should return to users with a

`CWMS-Data-Format-Deprecated: 2024-11-01 Format is not used often.`

Specific tasks:
- [x] #507 
- [x] #506 
- [x] #505 
- [x] #504 
- [x] #503 
- [x] #502 
- [x] #501 
- [x] #500 
- [x] #499 
- [x] #498 
- [x] #497

**Comment by RyanM-RMA** [comment]
@MikeNeilson how do you want us to provide the warning message to the caller?  Is this the response body, or an extra field or header?

**Comment by MikeNeilson** [comment]
It's in the title, as a header. The example above is probably good for the name itself. The content could use a little work. I'm not sure if date of removal or date of decision is best. Message should probably be optional.

**Comment by rma-rripken** [comment]
The header thing didn't make sense to me either until I read the linked notice ( https://github.com/USACE/cwms-data-api/issues/483)  So its a new http header added to the response.   I don't think we've done that anywhere yet but it should be possible.   @RyanM-RMA ping me if its not obvious how to add that header.

**Comment by RyanM-RMA** [comment]
@MikeNeilson all tickets associated with this ticket have been completed.  Please let me know if you have any additional review comments, or if we can close this ticket.
