### ISSUE TITLE
Switch processing of default accept header and simple names to newest format by default

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#485]
The following mapping should be followed

- `*/*` -> `application/json` -> default newest version
- 'application/json` -> default newest (e.g. for timeseries "application/json;version=2")

- `application/json;version=1` -> the original formats.
- `application/json;version=<X>` -> the exact requested format.

And except for `*/*`, the same for xml

For basins, `application/json` should load as `application/vnd.named+pg+json`

Specific tasks:
- [x] #507 
- [x] #506 
- [x] #505 
- [x] #504 
- [x] #503 
- [x] #502 
- [x] #501 
- [x] #500 
- [x] #499 
- [x] #498 
- [x] #497 
- [x] #527

**Comment by rma-rripken** [comment]
#526 Is asking for something similar but for Ratings - which I don't see in the list of tasks above.

**Comment by MikeNeilson** [comment]
Add it. It's only missing because I couldn't think of everything.

**Comment by RyanM-RMA** [comment]
@MikeNeilson all tickets associated with this ticket have been completed.  Please let me know if you have any additional review comments, or if we can close this ticket.
