### ISSUE TITLE
Add versioned mime type for original formats

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#486]
Add specific mime type "application/(json|xml);version=1" to refer to original formats when requested.

Specific tasks:
- [x] #507 
- [x] #506 
- [x] #505 
- [x] #504 
- [x] #503 
- [x] #502 
- [x] #501 
- [x] #500 
- [x] #499 
- [x] #498 
- [x] #497

**Comment by RyanM-RMA** [comment]
@MikeNeilson all tickets associated with this ticket have been completed.  Please let me know if you have any additional review comments, or if we can close this ticket.
