### ISSUE TITLE
may need to install /bin/bash in DockerFile?

### ISSUE THREAD

**Issue by ktarbet** [USACE/cwms-data-api#487]
Using the latest code with docker-compose.yml, I'm having a few issues.
I'm using  a fresh Ubuntu 22.04.3 LTS for host,  and Docker version 24.0.7

## First Issue: /bin/bash: 

```
hec@cda:~/cwms-data-api$ docker image ls

REPOSITORY                                  TAG           IMAGE ID       CREATED         SIZE
cwms-rest-api                               3.0-compose   c48ea5b48563   3 minutes ago   208MB
hec@cda:~/cwms-data-api$ docker run -it c4 /bin/bash
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
```
note: using /bin/sh  WORKS!
I can fix this by adding the following to DockerFile

```
RUN apk add --no-cache bash
```

## Second Issue - java.io.FileNotFoundException
```
java.io.FileNotFoundException: /opt/java/openjdk/jre/lib/: (No such file or directory)
```

Can fix with modifying docker-compose.yml to use:

-keystore /etc/ssl/certs/java/cacerts

## Third Issue - keytool error

keytool error: java.lang.Exception: Certificate not imported, alias <cda_lab_root> already exists

I'm not sure why it would already exist?   I tried changingt the alias to cda_lab_root1, and get a similar error.

**Comment by MikeNeilson** [comment]
Oops, I changed the base image for security issues and forgot to check the docker-compose setup.

For third issue that's a quirk of how the system is setup; I haven't been able to find a good way to deal with the recreation of that cert.

**Comment by ktarbet** [comment]
@MikeNeilson would you like a PR for this?

Is there a workaround for 'alias already exists'?

**Comment by MikeNeilson** [comment]
Not that I've found yet. It probably just needs a slighlty more complex script that checks for the error string and does a remove/insert. Since the error is on the alias, you wouldn't get a changed cert so just always replacing it would probably be best.

**Comment by ktarbet** [comment]
I'll work on a PR with these updates , that includes a script to import the cert with checks.

**Comment by MikeNeilson** [comment]
FYI, installing bash is probably good. the actual /bin/sh shell is "ash" which has some slightly different behavior.

**Comment by ktarbet** [comment]
Closing -- the fix was merged.
