### ISSUE TITLE
Update Endpoint: TimeZones

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#499]
Add deprecated header

Implement new style if not already done.

Task approval is for either doing, or PR, assign to self if planning to do the work.

**Comment by RyanM-RMA** [comment]
Hi Mike, what do you mean by "Implement new style if not already done"?  Is that using the Formats.parseHeaderAndQueryParam while passing in the query param and header?  Just wanting to make sure, cause that's what I understood and estimated for.

**Comment by MikeNeilson** [comment]
Oh, doing the rendering of data in Java instead of the database doing it.... really should've written it that way the first time.

Also, the deprecated header would be for the old database format, not the endpoint itself.

**Comment by RyanM-RMA** [comment]
Will that require a DTO?

**Comment by MikeNeilson** [comment]
... Maybe, It's a pretty constrained list so it doesn't really need to be paginated. The Java TimeZone class *might* be sufficient.

**Comment by RyanM-RMA** [comment]
It's the same for Units and Parameters btw.  Those three don't have DTO's, and they're using the db for formatting.
