### ISSUE TITLE
Update endpoint: basins

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#506]
create alias application/json alias for aplication/vnd.named+pg+json

This seems like a good idea since client might decide to just always send "application/json" or whatever, but maybe because it's so specific it's not required.

**Comment by RyanM-RMA** [comment]
@MikeNeilson can you elaborate on the description here?  is "application/json" going to be an alias for "application/vnd.named+pg+json"?  or the other way around?

**Comment by MikeNeilson** [comment]
`application/vnd.named+pg+json` is the formally correct content-type, `application/json` would be the alias, though now that you have the processing of "*/*" as the default, it's debatable if we should have a `appliation/json` alias. I say probably yes, just for consistency.

**Comment by RyanM-RMA** [comment]
Ok, that's what I was understanding from it, thank you for confirming.  I can support both the `\*/\*` and `application/json` for `application/vnd.named+pg+json`.  What about `application/vnd.pg+json`?  Is this an alias for the named piece, or is it separate?  From what I see in the code, it uses the same formatter so I would assume it's synonymous as well?

**Comment by MikeNeilson** [comment]
There's a difference between those two. Can't remember what it is off the top of my head, @rma-bryson wrote the initial code.

Something about some extra parameters I think.

**Comment by MikeNeilson** [comment]
This is likely a good example of "it ain't the default, if you want it you need to explicitly call it out." Not sure which should be the default, I would think the one with more information.
