### ISSUE TITLE
cwms/data/ratings/{rating-id} returns "Not Implemented" in most browsers

### ISSUE THREAD

**Issue by msweier** [USACE/cwms-data-api#526]
In the swagger page https://cwms-data.usace.army.mil/cwms-data, I can get a return for TraverseRES_Dam.Stage;Stor.Standard.Production for MVP office, and I can get data for the generated link (https://cwms-data.usace.army.mil/cwms-data/ratings/TraverseRES_Dam.Stage%3BStor.Standard.Production?office=MVP) in the Opera browser. 

In Chrome, Firefox, and Edge browsers I'm getting a "Not Implemented" for https://cwms-data.usace.army.mil/cwms-data/ratings/TraverseRES_Dam.Stage%3BStor.Standard.Production?office=MVP

**Comment by MikeNeilson** [comment]
That's odd. From the swagger page? It just worked for me in Firefox.
Was an "incident identifier" provided?

If you can recreate the error please provide the full error response.

**Comment by rma-rripken** [comment]
The issue is that just hitting the link in a browser doesn't send the needed accept header and we haven't defaulted the types or done the alias thing.
https://github.com/USACE/cwms-data-api/issues/485

**Comment by rma-rripken** [comment]
Doing the request from the swagger page adds the extra header and then it works.   Not sure why Opera would be different.

**Comment by msweier** [comment]
> If you can recreate the error please provide the full error response.

Seems like you guys have a bead on it but for posterity: 
{"message":"Not Implemented","incidentIdentifier":"-730284949424987388","details":{}}

**Comment by rma-rripken** [comment]
@msweier In your browser (Firefox,Chrome, IE etc) can you "Try it out" in the swagger-ui interface and build up your query and then "Execute" ?

Until we get something like that #485 issue implemented the request needs an extra header.  The swagger-ui sees that the header is needed and adds it by default.  

I've highlighted the extra header in this screenshot

![2024-01-31_9-17-30](https://github.com/USACE/cwms-data-api/assets/89810919/3cc9f580-264f-4e67-af43-2c79c1db8a16)

**Comment by msweier** [comment]
Sorry I wasn't clear. Yes the swagger page works in all browsers. So can the header be attached or embedded in the link somehow?

**Comment by rma-rripken** [comment]
From an html link?  No.  
Requests made from Java or Javascript or Python or the command-line can easily add the header.

**Comment by rma-rripken** [comment]
At the moment I don't think there are any code changes needed.  Communicating that header "application/json;version=2"  seems to be a stumbling block.  The tasks from #485 may improve things.  Should we add an html page that explains what is going on and how users can make V2 requests from Java, Javascript, Python, curl, wget etc?

**Comment by rma-rripken** [comment]
Mike - how do we resolve this issue - is there something CDA needs to do?   More documentation?  Different error messages if application/json provided but application/json;version=2 is needed?  Or do we implement #485 and count on that to resolve this?

**Comment by MikeNeilson** [comment]
#485 and the associated work seems like the best way to me. Probably wouldn't be too difficult to just make a minor edge case for just these, but would be better to just really do the "here's the default" work.
