### ISSUE TITLE
Connections getting held open on error

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#530]
I've found certain situtations where on some errors connections aren't returned. Over time this accumulates and causes pool exhaustion.

Still investigating, definitely happens when the connecting user has no appropriate office permissions which is strange because that handler is properly wrapped. (the suspect connection is in the Dao.init setting the session office. Implying that on error DSL::connectionResult doesn't result in a closed connection.

**Comment by MikeNeilson** [comment]
This is happen consistently in our cloud environment. I'm currently investigating more ways to force these errors.

**Comment by rma-rripken** [comment]
The first place I'd look is OfficeSettingConnectionProvider.getConnection(Connection conn, String office)
That happens after a connection has been acquired.   The acquire method there should probably have its own try/catch that closes the connection before throwing exceptions.     
Are you seeing specific messages in the logs?

**Comment by rma-rripken** [comment]
I haven't tested it, but this is the sort of thing you might try:
https://github.com/USACE/cwms-data-api/pull/531

**Comment by MikeNeilson** [comment]
Thanks, I'll keep that in mind. Other than the total failure case (e.g. the connecting user didnt' have permissions) I've having a hard time forcing the issue to happen locally. 

Started down the path of setting up some JMeter tests and Darren's going to get me some larger resources so I can test out if it's just number of connections being made or something over time.

**Comment by rma-rripken** [comment]
@MikeNeilson this has been fixed - right?

**Comment by MikeNeilson** [comment]
I believe so. between the changes you just made, the other recent changes, and the jmeter test I had setup I wasn't able to able to recreate the pool exhaustion with 1 connection a several parallel queries.
