### ISSUE TITLE
When are additional setOffice calls needed?

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#536]
In text-ts development I could not write text-ts unless I added an additional 
setOffice(c, "SPK") call immediately before the write attempt.
Before adding the setOffice call the exception was
Caused by: java.sql.SQLException: ORA-20048: NO_WRITE_PRIVILEGE: User doesnt have write privileges

LocationLevels just hit a similar problem and adding setOffice resolved it.  

#534 

Why are these setOffice calls now needed when they weren't needed before?
Doesn't OfficeSettingConnectionProvider  already set the session office Id for every connection?

Is it that OfficeSettingConnectionProvider is too early ?  If so, it seems like AuthDao should be setting it.

**Comment by MikeNeilson** [comment]
Since I user can have privileges in more than one office (our tests are even setup this way) when I went through setting the session it worked out better to pull the office out of the data itself rather than say a higher level parameter. Thus it gets set directly before the write.

I think I also had in mind a little "future proofing" where someone or something could write an array of data that included more than one office. Granted we don't support that at the moment.

**Comment by rma-rripken** [comment]
I'm not sure that all of our setOffice(..) calls are doing what we want them to. 

For example: 
https://github.com/USACE/cwms-data-api/blob/be6d0aa8892f51df641161ac0376694c61471431/cwms-data-api/src/main/java/cwms/cda/data/dao/Dao.java#L52
https://github.com/USACE/cwms-data-api/blob/be6d0aa8892f51df641161ac0376694c61471431/cwms-data-api/src/main/java/cwms/cda/data/dao/Dao.java#L76

Those end up calling CWMS_ENV.SET_SESSION_OFFICE_ID  but I believe jOOQ is getting a new connection from our DataSource for each of those calls and then closing the connection after the call is done.

https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/connection-vs-datasource/

This code:
https://github.com/USACE/cwms-data-api/blob/be6d0aa8892f51df641161ac0376694c61471431/cwms-data-api/src/main/java/cwms/cda/data/dao/LocationCategoryDao.java#L85C1-L88C6
Is an example of a pattern I think may be broken.  
The setOffice call gets into the Dao class code and does dsl.configuration() does its thing and then the create_LOC_CATEGORY does its thing but I don't think there is anything guaranteeing that those two calls get the same Connection.  

Maybe if they are using the same DSLContext instance (and they are) there is reason to think they will get the same connection?   I haven't seen anything that says that is true but maybe?  I would feel better about this if someone could point me at some jOOQ doc that explains what to expect.
