### ISSUE TITLE
CDA reporting 401 unauthorized on timeseries data interval failure

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#555]
The following Oracle stack trace is collected as an unauthorized user even though it is caused by invalid time series being stored to the timeseries.

```
Caused by: Error : 20998, Position : 0, Sql = BEGIN "CWMS_20"."CWMS_TS"."ZSTORE_TS" (:1 , :2 , :3 , :4 , :5 , cast(:6  as date), :7 , :8 ) ; END;, OriginalSql = { call "CWMS_20"."CWMS_TS"."ZSTORE_TS" (?, ?, ?, ?, ?, cast(? as date), ?, ?) }, Error Msg = ORA-20998: ERROR: ORA-06512: at "CWMS_20.CWMS_TS", line 5867
ORA-06512: at "CWMS_20.CWMS_TS", line 5862
ORA-06512: at "CWMS_20.CWMS_ERR", line 80
ORA-06512: at "CWMS_20.CWMS_TS", line 7094
ORA-20110: ERROR: Incoming data set contains multiple interval offsets. Unable to store data for TsVersionedTestLoc.Flow.Inst.1Hour.0.raw
ORA-06512: at "CWMS_20.CWMS_TS", line 5867
ORA-01422: exact fetch returns more than requested number of rows
ORA-06512: at "CWMS_20.CWMS_TS", line 5862
ORA-06512: at "CWMS_20.CWMS_TS", line 5466
ORA-06512: at "CWMS_20.CWMS_TS", line 9630
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)

```

**Comment by rma-rripken** [comment]
Why would that map to 401 and not 400 or even 500?  Thats weird.  What is the java exception that wraps it?

**Comment by adamkorynta** [comment]
The mapping is happening here: https://github.com/USACE/cwms-data-api/blob/develop/cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java#L291

Likely the schema needs to return different error codes to us.

**Comment by MikeNeilson** [comment]
Odd, that clearly doesn't match the error code returned.

**Comment by adamkorynta** [comment]
I would have expected the -20110 from: https://bitbucket.hecdev.net/projects/CWMS/repos/cwms_database/browse/schema/src/cwms/cwms_ts_pkg_body.sql#5870

**Comment by MikeNeilson** [comment]
Oh, it's both: `ORA-20110: ERROR: Incoming data set contains multiple interval offsets. Unable to store data for TsVersionedTestLoc.Flow.Inst.1Hour.0.raw`

20998 is the generic "error" code and the real error is lower in the trace.https://bitbucket.hecdev.net/projects/CWMS/repos/cwms_database/browse/schema/src/buildSqlScripts.py#4927
