### ISSUE TITLE
TimeseriesControllerTestIT could use JSONv1 tests

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#571]
If we continue to support Formats.JSONv1 we could use some integration tests.  Specifically tests that demonstrate/verify usage of the 'timezone' query parameter and how that affects(or not) the timezone of returned data.

I know we aren't doing new JSONv1 development but Timeseries is a pretty important end-point.  It would be nice to get better coverage, possibly even JSONv1 and JSONv2 interop.

**Comment by rma-rripken** [comment]
Related to #556

**Comment by MikeNeilson** [comment]
True, but given we're planning on just removing those by December I'm not really sure it's worth it.

**Comment by krowvin** [comment]
@MikeNeilson Can we enforce v2 for a period of time (as a default) if v1 is not specified? Giving people time to move to V2?

**Comment by MikeNeilson** [comment]
That is, in fact, the plan. We'll leave V1 in place but switch teh default. I have an open PR for that and just need to rebase and finish it.
