### ISSUE TITLE
"null" response body from CWBI-Test on /timeseries/category for office LRL

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#581]
![image](https://github.com/USACE/cwms-data-api/assets/47677856/9ae4e5fd-816a-4c72-b243-c8d56dd1231f)

Expected an empty JSON array if there are no categories

**Comment by rma-rripken** [comment]
Thats fun.  I see whats wrong.   If the DAO returns an empty list would you rather get "[]" or something like 204 NO_CONTENT?
