### ISSUE TITLE
Timeseries API returns Null Values for Queries Outside Data Range for Reg. TS

### ISSUE THREAD

**Issue by msweier** [USACE/cwms-data-api#629]
If a regular timeseries is queried outside of the timeseries extent, datetimes, null values, and qualifiers are returned. This is not desirable for large, period of record pulls because it results in a large data transfer. It would be better if it didn't return anything if it's outside the range.

Let's say I want to merge 15min regular data with 1 hr regular data using cwms-python. I would have to query the extents of the timeseries using the catalog endpoint and them build my query off of those extents. Could CDA first query the extent of a regular timeseries from the timeseries end point and then know not to manufacture null values for data that doesn't exist?

Note, this occurs in the CDA 3.1.3.
![image](https://github.com/USACE/cwms-data-api/assets/9432394/0eb6db05-144f-4b98-a630-8b45835a35fa)

**Comment by rma-rripken** [comment]
A "trim" flag was recently added.  Does that help?

**Comment by msweier** [comment]
Thanks, I think it would! I would expect that would've been the default behavior, but maybe there are use cases I'm not thinking of for creating the null values.

**Comment by msweier** [comment]
Tagging @Enovotny to track as well

**Comment by Enovotny** [comment]
@rma-rripken can the trim flag default to True?  So the default is to have the values trimmed?

**Comment by rma-rripken** [comment]
I don't see why not.  Lets check that cwms-data-access-client is making use of the flag and then I think we can make the default whatever you want it to be.
