### ISSUE TITLE
Timeseries Write Payload limit of 20,000

### ISSUE THREAD

**Issue by msweier** [USACE/cwms-data-api#632]
There appears to be a write payload limit of 20,000 or so records at the timeseries end point. I was using cwms-python to merge period of record data. The workaround is to break up the store, but it makes clunky code. Not sure if this if a hard and fast limitation of CDA. If it is, maybe cwms-python could include something to handle it. 

![image](https://github.com/USACE/cwms-data-api/assets/9432394/c58ae7fe-b5e4-4d03-abab-a2b60925f62a)

**Comment by MikeNeilson** [comment]
Hmm, we'll have to check the default payload sizes. I'm pretty sure the defaults for upload are rather small. Can you please provide here the raw request? E.g. exactly what should be sent, or at least the body.

**Comment by msweier** [comment]
Well it's in the cwms-python wrapper, but if I limit it to 20,000 records it stores, if it's 25,000 it fails. It is an irregular timeseries.
`combined_data = cwms.timeseries_df_to_json(data = combined_df.head(25000), tsId = 'LockDam_02.Stage.Inst.~15Minutes.0.test', units = units, office_id = OFFICE)`

`cwms.store_timeseries(data=combined_data)`
![image](https://github.com/USACE/cwms-data-api/assets/9432394/8ba268a3-f3f9-4907-a0c6-c4974ceab0d0)

**Comment by MikeNeilson** [comment]
Yeah, the server can be configured to allow more, I just want to see the raw JSON (starting at [29]: but not an image) so we can see the actual size in bytes as that's what the error is based on.

**Comment by msweier** [comment]
I think it's probably a 1 MB limit. I suppose I could do a little rounding on the stage to help.
![image](https://github.com/USACE/cwms-data-api/assets/9432394/e7303cf3-1804-403a-9fb2-02890b61857a)
[Uploading data.json…]()

**Comment by MikeNeilson** [comment]
Yeah, that'll do it. I guess the question would be just how common this volume of data will be?
I'm not opposed to increasing it, I can think of a few rating tables that would need it as well.

**Comment by msweier** [comment]
Probably not that common, but if this is our tool to read/write to the database, it is going to happen here and there. I'm doing a little housekeeping in the DB while testing CDA/cwms-python. 

Is it possible to have the volume increase if we are on the Corps network or a flag? Another option would be wrap the solution in cwms-python.

**Comment by MikeNeilson** [comment]
That particular setting would only be for authenticated users so just increasing it isn't a huge deal. Any malicious person can already just send a larger payload to try and cause problems. I just need to go see if it's a application level parameter or a server parameter, pretty sure server.

**Comment by krowvin** [comment]
> pretty sure server
   
I saw some mentions of size limits but was unable to find any reference to a hard POST limit. Following along to see where that is set!

**Comment by msweier** [comment]
For 15 minute data, it comes out to be about 9 months (e.g. 25,000/(4x24x30) = 8.7 months) would hit that limit, so maybe somewhat common? Getting approved USGS data sometimes has us scraping back 3 years!

**Comment by MikeNeilson** [comment]
I mean, there is at least *A* hard limit for size, but we can go pretty big, or we can do different techniques (which cwms-python) can wrap to allow such bulk upload.

**Comment by msweier** [comment]
I'll let @Enovotny weigh in on that one.

**Comment by rma-rripken** [comment]
We hit a similar limit and error message on one of the other end-points.  I think we could change the processing on the CDA side of things and open it up quite a bit.

**Comment by rma-rripken** [comment]
It was the BinaryTimeSeriesController.  There is a different way to process the user's POST.   There is still eventually a limit (memory).  I think the default size via the current way of doing things is 1MB.  We can adjust that knob higher (within reason) or we can change the code to stream what the user has POST'd and the limit becomes whatever jackson or jaxb can do with the memory available.   I was able to get into the GB range without trouble

**Comment by Enovotny** [comment]
should this be handled to have the message split and stored in parallel?  Set a limit on size if it is larger split into multiple message that are stored in parallel for faster processing time?  Can this be done in the background in CDA?  If not we could do it in cwms-python.  divide the values field into multiple messages.

**Comment by rma-rripken** [comment]
I suggest we change the CDA side to handle large messages before changing anything else.  Its an easy fix on the CDA side.

**Comment by MikeNeilson** [comment]
I'm with Ryan, we definitely still have a lot of room on the server before we absolutely need to to the write in parallel. It's just the the defaults end up being rather small (for our usage.)

**Comment by msweier** [comment]
@rma-rripken and @MikeNeilson, what is the payload limit? I just ran into a 500 error w/ a 22.9 MB payload and am wondering if it is related. I broke it up into two payloads and it saved. Some of the period of record USGS data can get pretty big.

**Comment by MikeNeilson** [comment]
I'll have to dig, technically it can be controlled at several different levels so it may be a Tomcat property to set, not CDA itself.

**Comment by msweier** [comment]
Nevermind @MikeNeilson, I think there is something else going on because I just saved a 24.5 MB payload without issue. Not sure what the issue is though.

**Comment by MikeNeilson** [comment]
Could just be that the first instance something too just long enough that the connection timed out. Keep an eye on it though and test more if you have the time. It could me that we do need to setup an async write were we just return a "task id" and you poll for when it's done.
