### ISSUE TITLE
Need River Mile (station) in CDA 

### ISSUE THREAD

**Issue by inguyen314** [USACE/cwms-data-api#633]
I need to grab the river mile for my report using CDA.  

I uses the following query to get it.  
```sql
select station, station_unit, drainage_area, area_unit
from cwms_20.av_stream_location
where location_id = 'St Louis-Mississippi'
and unit_system = 'EN'
``` 
Which could return a payload like:
```json
{
    "station": "179.6",
    "station_unit": "mi",
    "drainage_area": "6.97E+005",
    "area_unit": "mi2"
}
```  
Please help add this to CDA. thank you

**Comment by MikeNeilson** [comment]
That support is convered in the next contract, which conviently just got awarded. But in the meantime try the existing Basin API, it's probably going to give you may more info than you really need but is currently they only way I can think of to get stream data (well, assuming I'm remembering how it works correctly.)

**Comment by inguyen314** [comment]
thank you

**Comment by krowvin** [comment]
@MikeNeilson districts are using rivermile more, especially on their public site. Can we assign funding to this?

**Comment by MikeNeilson** [comment]
Shouldn't need any extra, RMA is currently working on Stream data. @rma-psmorris .

**Comment by rma-psmorris** [comment]
@inguyen314 this is being worked on right now. @rma-bryson @zack-rma Can you two add links to your Basin and Stream DTO PRs for Ivan to reference the JSON?

**Comment by zack-rma** [comment]
Here's the PR for the Basin DTO: https://github.com/USACE/cwms-data-api/pull/714

**Comment by rma-bryson** [comment]
The Stream DTOs are currently undergoing an update. This PR is currently under review: https://github.com/USACE/cwms-data-api/pull/749/files#diff-30a376d797e17c6c26004664c481ce2e10dac443f0f70b69efaa719f57fdd4ad

The above PR doesn't change the existing stream dto. You can find the stream.json example in this PR: https://github.com/USACE/cwms-data-api/pull/739/files#diff-f49ef6c43c188363f3da2400f4affe8ad3b29b543deaae3a8397f9282968f9d2
