### ISSUE TITLE
timeseries category timeseries-caegory-like and timeseries-group-like returns no data

### ISSUE THREAD

**Issue by Enovotny** [USACE/cwms-data-api#635]
the timeseries-category-like, timeseries-group-like parameters don't appear to work for the timeseries catelog.  It returns a blank dictionary when using.  Tried multiple regular expressions.  Would also like timeseries timeseries-group-like/timeseries-caegory-like parameters to work for location catelog.  only return locations that have timeseries in that timeseries-group, but that might be a separate issue.

![image](https://github.com/USACE/cwms-data-api/assets/9612217/73c7b8d6-db5c-4a11-b7b2-dc86c427b6b6)

![image](https://github.com/USACE/cwms-data-api/assets/9612217/ef7902e3-2374-42cc-9ec0-752c184c2253)

![image](https://github.com/USACE/cwms-data-api/assets/9612217/406753bc-2495-4295-a124-be55bfaca8f1)

**Comment by MikeNeilson** [comment]
Try it again on CWBI, we made some changes recently that I don't think have been pushed to cwms-data.usace.army.mil yet.

**Comment by Enovotny** [comment]
it is the same on CWBI-test.

**Comment by rma-rripken** [comment]
I see what is wrong with the query.  Its looking for rows where aliased_item is null but loc_alias_group, loc_alias_category, ts_alias_group and ts_alias_category are always null when aliased_item is null.
