### ISSUE TITLE
V1 Timeseries Returns Values when no Office Present

### ISSUE THREAD

**Issue by krowvin** [USACE/cwms-data-api#642]
A user reported they *could* get values using V1 without specifying the office. 

## Should we *consider making Office *required* for the timeseries endpoint*?

![image](https://github.com/USACE/cwms-data-api/assets/23619282/ea57b673-3b8e-487e-8485-3196c25888fc)

It won't hurt V1 and would fix the issue brought up below with V2. 

```bash
curl --location 'https://cwms-data.usace.army.mil/cwms-data/timeseries?name=Troy-Cuivre.Stage.Inst.15Minutes.0.lrgsShef-rev&begin=2024-05-09T09%3A00-05%3A00'

```

Querying using V1 gives:
```json
{
    "time-series": {
        brevity
        "time-series": [
            {
                "office": "MVS",
                brevity
                "regular-interval-values": {
                    "segments": [
                        {
                           brevity
                            "values": [
                                [
                                    8.25,
                                    0
                                ],
                                [
                                    8.24,
                                    0
                                ],
                                [
                                    8.24,
                                    0
                                ]
                            ]
                        }
                    ]
                }
            }
        ]
    }
}
```

Knowing that an office is required to find data using V2 (Are there docs to this? I/we know it from experience)
```bash
curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/timeseries?name=Troy-Cuivre.Stage.Inst.15Minutes.0.lrgsShef-rev' \
  -H 'accept: application/json;version=2'
```
gives
```json
{
    "message": "Not found.",
    "incidentIdentifier": "-178818237359880300",
    "details": {}
}
```
Where it makes sense it would not be found, but it's *not* obvious to the end user that this is because the office is missing. (this happened)
```bash
curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/timeseries?name=Troy-Cuivre.Stage.Inst.15Minutes.0.lrgsShef-rev&office=MVS' \
  -H 'accept: application/json;version=2'
  ```
  And then adding the office=MVS (in this case) fixes it __(for the future reader with this problem)__

**Comment by rma-rripken** [comment]
We can mark parameters as required in the swagger annotations but that wouldn't work in this case b/c it is optional in V1.  
There is already an issue to go thru the controllers and determine if all the parameters that are marked as required actually are required and to document when one is required in V2 but not in V1.   https://github.com/USACE/cwms-data-api/issues/562

There is a Controllers helper method for getting required parameters from the request context that should be used when a parameter is required.  When that method is used and the parameter isn't included then the user will get a sensible error message explaining which required parameter isn't provided.  

Easily fixable on a case-by-case basis.  I envision #562 as a more systematic approach.

**Comment by krowvin** [comment]
>  it is optional in V1  

Suppose the choice is nice. At first I was just thinking adding it to the annotations and not actually enforcing it on the API itself. 

Even just a note about it is helpful. Thank you for hopping on this! I know it has come up a few times, and again today. Thought to document it for new users being onboarded to the API.
