### ISSUE TITLE
CDA call to return base_location/sub_location hierarchy/Intent vs design question and sub locations

### ISSUE THREAD

**Issue by JeremyDKellett** [USACE/cwms-data-api#652]
Is the design intent of CDA to replicate the API calls available in the CWMS API?

Could we get one like the below endpoint (which might change, but the json return is below too). 

Intent: one call to obtain the sub locations of a project/location
Discussion: looking at the /locations end point (https://cwms-data.usace.army.mil/cwms-data/swagger-ui.html) and the catalog end point I don't see a way to determine the base/sub location hierarchy of location in CWMS without obtaining the entire locations end point and then inferring it client side. I can see a use-case where districts don't necessarily have TS IDs (thus not in the TS Catalog) for each sub location. 
Disclaimer: if this is solved but not yet on the cwms-data.usace.army.mil then please point me the correct way :)

SELECT * 
 FROM cwms_v_loc
 WHERE base_location_id = :location_id
 AND unit_System = 'EN' --suggest having unit system be a selectable option with default to 'EN'

// 20240517190621
// https://reservoircontrol.usace.army.mil/nae_ords/cwmsweb/projects/cwms_v_loc/UVD/sub_locations

{
  "items": [
    {
      "location_code": 68511521,
      "base_location_code": 8177021,
      "db_office_id": "NAE",
      "base_location_id": "UVD",
      "sub_location_id": "Gate 01",
      "location_id": "UVD-Gate 01",
      "location_type": null,
      "unit_system": "SI",
      "elevation": 128.01600000000002,
      "unit_id": "m",
      "vertical_datum": "NGVD29",
      "longitude": -72.256234168,
      "latitude": 43.794220846586,
      "horizontal_datum": null,
      "time_zone_name": "Unknown or Not Applicable",
      "county_name": "Orange",
      "state_initial": "VT",
      "public_name": "Gate 1",
      "long_name": null,
      "description": null,
      "base_loc_active_flag": "T",
      "loc_active_flag": "T",
      "location_kind_id": "OUTLET",
      "map_label": "Gate 1",
      "published_latitude": 0,
      "published_longitude": 0,
      "bounding_office_id": "NAE",
      "nation_id": "UNITED STATES",
      "nearest_city": "Lebanon",
      "active_flag": "T"
    },
    {
      "location_code": 68512521,
      "base_location_code": 8177021,
      "db_office_id": "NAE",
      "base_location_id": "UVD",
      "sub_location_id": "Gate 02",
      "location_id": "UVD-Gate 02",
      "location_type": null,
      "unit_system": "SI",
      "elevation": 128.01600000000002,
      "unit_id": "m",
      "vertical_datum": "NGVD29",
      "longitude": -72.25614,
      "latitude": 43.794,
      "horizontal_datum": null,
      "time_zone_name": "Unknown or Not Applicable",
      "county_name": "Orange",
      "state_initial": "VT",
      "public_name": "Gate 2",
      "long_name": null,
      "description": null,
      "base_loc_active_flag": "T",
      "loc_active_flag": "F",
      "location_kind_id": "OUTLET",
      "map_label": "Gate 2",
      "published_latitude": 0,
      "published_longitude": 0,
      "bounding_office_id": "NAE",
      "nation_id": "UNITED STATES",
      "nearest_city": "Lebanon",
      "active_flag": "F"
    },

**Comment by rma-rripken** [comment]
The location catalog query can probably get you those with the 'like' parameter
^UVD-.+

curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/catalog/LOCATIONS?unit-system=EN&office=NAE&like=%5EUVD-.%2B' \
  -H 'accept: application/json;version=2'

**Comment by JeremyDKellett** [comment]
Sweet, I can work with that on the UI side. thx.

**Comment by MikeNeilson** [comment]
FYI, our design philosophy is documented in the wiki section: https://github.com/USACE/cwms-data-api/wiki/API-Design
(It's also not set in stone, so feel free to open discussions or issues if you disagree with any portion of the philosophy... I did basically make it up on the stop.)

**Comment by JeremyDKellett** [comment]
its all good... I looked at the /location end point not the /catalog/locations endpoint and def. can do what I was looking for from catalog/locations. 

That said, I'm not sure it'll work for our areas of interest (as in downstream lat/lons we make notes about but aren't necessarily a great sub location of project) like bridges or a historic sloughing point, etc.
