### ISSUE TITLE
Add most recent or currently effective to cwms-data/rating/{rating-id}

### ISSUE THREAD

**Issue by Enovotny** [USACE/cwms-data-api#693]
add a parameter or a way to grab the most recent or currently active rating curve from the cwms-data/rating/{rating-id} endpoint

currently to get the most recent I can run this end point using method=Lazy to get all of the effective and creation dates.  then run it again with the effective date in the Begin field to rating curve with the most current effective date.  Would be nice to have this done internally or in a more efficient manor.  

This would be based on most recent according to effective date.  As in if someone was creating a rating for a time of now what rating curve would be used.

**Comment by Enovotny** [comment]
maybe a more uniform utility would be to add a parameter effective date or something like this.  User can enter a date and it will grab whatever rating curve that would be effective for that date.  if today's date it would pull the current effective rating curve.

**Comment by MikeNeilson** [comment]
Nearest to the provided effective date, based on the spec of the table makes sense. To me so does "now" if no date if provided.

**Comment by adamkorynta** [comment]
I can definitely see adding a floor + ceiling operator given temporal interpolation and transition dates, but a single effective date could be misleading. The need for the latest curve also makes sense and could also be accomplished by a floor + ceiling operation with the begin/end being the same, though I do think a `/{ratingid}/latest` type endpoint would simplify things. Also, I presume we'd want to filter out inactive curves from the search.

**Comment by MikeNeilson** [comment]
Oh yeah, certainly remove inactive by default. as for a `/latest`, I agree that makes sense. Would probably make sense for location levels as well and we already do that for timeseries.

**Comment by adamkorynta** [comment]
Closing this ticket, can create a new ticket if a floor/ceiling for a given date is needed
