### ISSUE TITLE
TimeSeries format parameter used in combination with accept header is confusing

### ISSUE THREAD

**Issue by rripken** [USACE/cwms-data-api#72]
The TimeSeriesController only returns the application/json;version=2 response if the header includes accept = application/json;version=2  AND the format parameter is not specified.  

If the format parameter is specified (format=json) and the accept header is specified then the old pl/sql json output is returned.

Do we need to check for the accept header version if format=json is specified?
Or do we need to add a format=json2 output (not my favorite solution)?  
Or do we throw an exception if both are specified?

Perhaps the documentation needs to be updated.

**Comment by MikeNeilson** [comment]
https://github.com/USACE/cwms-radar-api/blob/708f04e11454ddb0c07911d2dad5d5f67662d233/cwms_radar_api/src/main/java/cwms/radar/formatters/Formats.java#L174

The current logic is use the query string by default. My thought was that it would break existing clients, but I think changing that to return an error if both are specified is the better choice.
