### ISSUE TITLE
TimeSeries element names mismatch reported swagger schema 

### ISSUE THREAD

**Issue by rripken** [USACE/cwms-data-api#73]
The TimeSeries object is annotated with swagger @Schema tags that don't always match the names of the returned xml elements.
officeId vs office-id
pageSize vs page-size
valueColumns vs value-columns

This seems like an aesthetics except that codegen libraries want to use the schema to create objects that interact (and serialize/deserialize) with the api so I think we need the tags to match the schema

**Comment by MikeNeilson** [comment]
Agreed, the schema tags should match what we're given. I think this was just an oversight in our effort to get stuff out.

**Comment by adamkorynta** [comment]
The catalog API is the same way 
nextPage -> next-page
pageSize -> page-size

Let me know if you want a separate ticket for that API.

**Comment by rripken** [comment]
I think I've fixed this in PR #103
