### ISSUE TITLE
Remove query done during every Dao construction

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#735]
Every DAO object that gets constructed calls into the Dao.java constructor which executes a query to retrieve the database version. 

```
version = dsl.connectionResult(c -> DSL.using(c,SQLDialect.ORACLE18C)
                .select(AV_DB_CHANGE_LOG.VERSION)
                .from(AV_DB_CHANGE_LOG)
                .orderBy(AV_DB_CHANGE_LOG.VERSION_DATE.desc())
                .limit(1)
                .fetchOne().component1());
```

Sure its a small query but its being done over and over when A) The version is not likely to change B) Most things don't do anything with the version.

Can we move the version retrieval into just the places that do something with it?
Can we only do the retrieval on-demand?
Can we cache the version retrieval?  If so, what is a reasonable expiry? Once an hour?  

Is it possible for CDA to remain running during a schema update to the point that CDA would be able to detect and appropriately respond to schema changes without restart?  It would be cool to try and see it work.

**Comment by rma-rripken** [comment]
We used CacheBuilder in TimeSeriesDaoImpl - a similar cache could be added to Dao.java with about an hour of effort.

**Comment by MikeNeilson** [comment]
Point of use is probably best. That would allow CDA to survive a schema update that didn't otherwise distrupt it's operations. but given the use of the pool it does basically stay running even in light of those failures.
