### ISSUE TITLE
Timeseries Catalog returns incorrect number of elements per page when exclude-empty=true is used

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#748]
At it says, if exclude-empty is set to true, less than page-size results are returned, which prevents the next-page marker from showing up.

**Comment by zack-rma** [comment]
I was unable to recreate this issue. Is there a case where there is not an extents entry associated with a Timeseries?

**Comment by MikeNeilson** [comment]
Several in the national databases. But let's check the catalog code for recent changes though. I remember tweaking that query a few weeks ago but don't remember if I opened this issue from that work, or just forgot to reference and close it.

**Comment by MikeNeilson** [comment]
This was fixed as part of #744 and not correctly linked. Thanks for checking again though.
