### ISSUE TITLE
TimeSeries begin and end without timezone throws IllegalArgumentException exception.

### ISSUE THREAD

**Issue by rripken** [USACE/cwms-data-api#75]
The begin and end parameters are documented to default to UTC if no timezone is specified but in testing that results in the server throwing an IllegalArgumentException "Time cannot contain only an offset without the timezone."

I refactored the Dao code around this exception to try and and make sense of how the values were being parsed but I'm not entirely sure why it was being thrown.  Perhaps it can be removed?

**Comment by MikeNeilson** [comment]
@DanielTOsborne 
I assume this block was created when you were implementing your changes to TimeSeries?

https://github.com/USACE/cwms-radar-api/blob/708f04e11454ddb0c07911d2dad5d5f67662d233/cwms_radar_api/src/main/java/cwms/radar/data/dao/TimeSeriesDaoImpl.java#L135

**Comment by DanielTOsborne** [comment]
> @DanielTOsborne I assume this block was created when you were implementing your changes to TimeSeries?
> 
> https://github.com/USACE/cwms-radar-api/blob/708f04e11454ddb0c07911d2dad5d5f67662d233/cwms_radar_api/src/main/java/cwms/radar/data/dao/TimeSeriesDaoImpl.java#L135

Yes.
If the timezone argument wasn't supplied, it would check to see if the supplied datetime contained an offset+timezone in the string, and use that if so. Makes the formatting/parsing of query parameters and results round-trip and easier to process.

Basically, you can use a ZonedDateTime with ISO_FORMAT to both create the query parameter, and then read the date again later in the result.

**Comment by MikeNeilson** [comment]
I'm not sure it's working correctly:

`curl -X 'GET' \
  'http://localhost:8384/cwms-data/timeseries?name=Alder%20Springs.Precip-Cum.Inst.1Hour.0.Calc-val&office=SPK&unit=in&begin=2021-11-01T13%3A00%3A00&end=2021-11-03T17%3A00%3A00' \
  -H 'accept: application/json;version=2'` (adjust the host/port as required) 

is throwing the error.

**Comment by DanielTOsborne** [comment]
Looks like an edge case, apparently UTC's zone is the same as its offset.
I wonder if it's an OS difference? I don't remember hitting this in my tests, but I also tested on Windows.
Clearly timezones are hard.

**Comment by DanielTOsborne** [comment]
The fix will involve changing DateTimeFormatter.ISO_DATE_TIME on https://github.com/USACE/cwms-radar-api/blob/708f04e11454ddb0c07911d2dad5d5f67662d233/cwms_radar_api/src/main/java/cwms/radar/data/dao/TimeSeriesDaoImpl.java#L128 and https://github.com/USACE/cwms-radar-api/blob/708f04e11454ddb0c07911d2dad5d5f67662d233/cwms_radar_api/src/main/java/cwms/radar/data/dao/TimeSeriesDaoImpl.java#L129 to an explicitly specified pattern, as in that pattern, the offset and timezone are both optional, and the timezone is optional even if the offset is specified.
Hence the check.
I can work on this in the next few days.

**Comment by MikeNeilson** [comment]
> 
> ...
> Clearly timezones are hard.

Truer words, I'm not sure they've been spoken.

**Comment by MikeNeilson** [comment]
Oh, that could also be a java version issue.
