### ISSUE TITLE
Integration test results

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#778]
In lieu of actually having the automated tests running correctly... possible tomorrow, most likely week after next though. He's a report from my machine.

I'm going to do this at least once a day until we have the automation, as it should motivate me to you know, do that. But in the mean time it gets some feedback faster.

The basic setup is a fresh install with the default settings, so HQ and no users set but the installed ones. There's a file in the test directory were you can make new "cwms users" as needed,  adding the user again is a "no op" in cwms so there's no failures to worry about with duplication.

I'm pretty sure some of the test are failing because the work isn't complete and in progress. I recommend just annotating the class with `@Disabled("<a reason>")` so this report can be more focused.

Also I'm just going to keep adding each report to this issue.

**Comment by MikeNeilson** [comment]
[integrationTests-2024-07-11.zip](https://github.com/user-attachments/files/16182783/integrationTests-2024-07-11.zip)

Notable failure: VersionedTimeSeriesController.

**Comment by MikeNeilson** [comment]
@zack-rma FYI.

**Comment by rma-rripken** [comment]
I see the problem with versioned and have a fix for it.   The problem with Projects has already been fixed in [a different](https://github.com/USACE/cwms-data-api/pull/712) pr that is waiting for you to resolve comments

**Comment by msweier** [comment]
> I see the problem with versioned and have a fix for it. The problem with Projects has already been fixed in [a different](https://github.com/USACE/cwms-data-api/pull/712) pr that is waiting for you to resolve comments

I'm attempting to write a versioned TS w/ CDA 3.1.3 and getting a 500 error. Would this issue you @rma-rripken are referring to be the reason?
`{
  "message": "Internal Error",
  "incidentIdentifier": "-7273730038755828008",
  "details": {}
}`

**Comment by MikeNeilson** [comment]
It's quite likely. if you are doing this on your T7 the next RC that gets output should have the fix merged in.

**Comment by rma-rripken** [comment]
@msweier  Unfortunately that doesn't have enough info for me to know if its related or not.  CDA doesn't give users the full details.  You'd need to match up that incidentIdentifier with the message and stack trace that is probably in the tomcat logs.  My comment was in response to the failed integration tests that Mike posted in the zip.  Coverage is not perfect but most of the end-points have integration tests verifying functionality

**Comment by msweier** [comment]
Just tested Release 3.1.5-RC06-SNAPSHOT and versioned timeseries worked like a charm! Thanks guys! 
![image](https://github.com/user-attachments/assets/e2c5679d-e133-498f-af03-745bd691ab6c)
