### ISSUE TITLE
Timeseries API needs IntervalOffset and Location Time Zone added

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#79]
In order to distinguish between Local Regular Time Series (LRTS) and Pseudo Regular Time Series (PRTS), we need the interval offset metadata returned (preferably in seconds), and the location's time zone.

**Comment by rripken** [comment]
These were added to the ts Catalog but its requested they be added to TimeSeries as well.

**Comment by rripken** [comment]
@rma-psmorris was going to rewrite this query a better way.
