### ISSUE TITLE
Timeseries GET request sends error code 500 on time series not found

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#80]
We would like the ORA-20025 SQLException code to send out an error code 404 instead so that the client API's can handle it appropriately.

**Comment by rripken** [comment]
#106  Should address this for version 2 getAll requests.

**Comment by MikeNeilson** [comment]
I think you're probably right, but good idea to verify just in case something got missed.

**Comment by MikeNeilson** [comment]
Can someone verify this actually happened?

**Comment by krowvin** [comment]
@rma-rripken Can we close this?

**Comment by rma-rripken** [comment]
yes
