### ISSUE TITLE
Catalog/timeseries API needs IntervalOffset and Location Time Zone added

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#81]
In order to distinguish between Local Regular Time Series (LRTS) and Pseudo Regular Time Series (PRTS), we need the interval offset metadata returned (preferably in seconds), and the location's time zone.

The current CWMS radar client implementation does not need the active flag or user privileges metadata as far as I am aware.

**Comment by MikeNeilson** [comment]
before I add that. I was considering removing the catalog endpoint in favor of having The timeseries controller getAll return the list. Having started to use the API what are your thoughts on that? Does an end point specifically for a catalog of info make more sense to you?

**Comment by MikeNeilson** [comment]
Well, slight snag. We're currently developing against a version of the db that doesn't include that in the view. Not a huge deal but will take a little longer to deal with the change in a clean way.

**Comment by adamkorynta** [comment]
I'm in favor of moving the catalog/timeseries to a timeseries endpoint. It'll cleanup the schema for sure. I wonder about the separation between data and metadata. If /timeseries returns data and /timeseries/metadata or something similar.

**Comment by MikeNeilson** [comment]
perhaps /timeseries/catalog? Make sure the intention is clear.
