### ISSUE TITLE
HTTPS connection  - 'obsolete connection settings'   python says: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] 

### ISSUE THREAD

**Issue by ktarbet** [USACE/cwms-data-api#824]
I'm not able to access the API when using a newer versions of Python 3.10 or higher.    The error below happens:

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000

For a test I used Chrome, to eliminate Python, and I get this message, with chrome developer tools, accessing  https://cwms-data.usace.army.mil/cwms-data/swagger-ui.html

![image](https://github.com/user-attachments/assets/4097abd1-b65d-4816-b95e-7f2658765d38)

```
Connection - obsolete connection settings

The connection to this site is encrypted and authenticated using TLS 1.2 RSA , and AES_256_CBC with HMAC-SHA1.

RSA key exchange is obsolete. enable an ECDHE-based cipher suite AES_256_CBC is obsolete. Enable an AES-GCM-based cipher suite.
```

To reproduce the error in Python see the steps below.

```
(test) C:\Temp>python
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> url = "https://cwms-data.usace.army.mil/cwms-data/swagger-ui.html"
>>> response = requests.get(url)
```

error message below

```
Traceback (most recent call last):
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Programs\Anaconda3\envs\test\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cwms-data.usace.army.mil', port=443): Max retries exceeded with url: /cwms-data/swagger-ui.html (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Anaconda3\envs\test\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='cwms-data.usace.army.mil', port=443): Max retries exceeded with url: /cwms-data/swagger-ui.html (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))
>>>


```

**Comment by krowvin** [comment]
Karl, 

This is almost certainly an issue with the ciphers returned via edge proxy on the cwms-data server. 

I will investigate internally to see what we can do about this. 

For now, because the data is not sensitive, I would be curious if setting the request to 

```python
r = requests(URL, verify=False)

```

At least bypasses the issue so you can continue to work. 


Or set older certs yourself but that's a little more involved.

**Comment by ktarbet** [comment]
```
r = requests.get(url,verify=False)   
```
is not working for me.  My workaround is to use an older version of Python  :(   So I'm able to work.

**Comment by krowvin** [comment]
A bummer indeed! 

Must be newer ciphers(?) entirely then and I don't think the API accepts non SSL queries. But I haven't tried either. 

Will see what IT comes up with if anyone else doesn't have any ideas.

**Comment by adamscarberry** [comment]
I had the same issue with newer versions of Airflow.  I wasn't able to workaround the error.  I think it comes down to SSL v3 being a deprecated standard and python is not going to support it.

Related: https://github.com/urllib3/urllib3/issues/2200

**Comment by ktarbet** [comment]
Thanks for the updates.  Here are my current results:

![image](https://github.com/user-attachments/assets/e50864d8-0490-4c7d-879d-f5cb67720087)

(test) C:\project\DSSVue-Example-Scripts\src>python
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> url = "https://cwms-data.usace.army.mil/cwms-data/swagger-ui.html"
>>> response = requests.get(url)
>>> print(response)
<Response [200]>

**Comment by krowvin** [comment]
Excellent! Glad that worked for you Karl. 

# For others wondering what fixed it

IT was able to update the cipher settings on our edge proxy to more modern standards (seen in Karl's screenshot)

We confirmed early on that internal access to CDA only had issues related to the SSL cert it uses (not the public one seen in Karl's screenshot/digicert), this will also be addressed but isn't used normally since all go through the public domains. 

@adamscarberry you might see if you are able to use newer versions in Airflow now. I also found the post you linked and safe to say anything post 3.10 will raise that. I know most Corps employees have been using 3.9 and below.

**Comment by ktarbet** [comment]
thanks @krowvin 😄

**Comment by Enovotny** [comment]
@krowvin Does this fix issues with connecting to district T7s or just national database/CWBI.  Is the fix in CDA and does it require a new CDA install to work at districts?

**Comment by MikeNeilson** [comment]
I don't recall the T7s being affected, the issue was an upstream component having outdated settings. all of the lower level infra has the correct settings. The changes are at the Tomcat or other proxy level not in CDA, CWMS-Python, or the Database.

I don't CWBI would've had the issue, they keep they're reverse proxies reasonably up-to-date.

**Comment by krowvin** [comment]
> @krowvin Does this fix issues with connecting to district T7s or just national database/CWBI.  Is the fix in CDA and does it require a new CDA install to work at districts?

This fixes just for the national CDA instance on https://cwms-data.usace.army.mil/cwms-data

No new CDA required. The above server should work with python 10+ now. 

The issues with internal CDA required verify=False is tied to the certchain not being properly setup. At least that's my understanding. Does this sound right to you? If so I could ask IT to investigate this too, although I wager it is a larger task item. 


No new CDA instances and/or installs required in either case. (Upstream like Mike says)


As for CWBI I'm not sure what ciphers and/or certs are setup there. @willbreitkreutz  may have a better idea.

**Comment by Enovotny** [comment]
Thanks.  For local instances I have working on my local windows machine and I just tested it with a 3.11 environment and it works,  The issue I am having is on my VM so it might be related to access to certificates on the VM and the type of certificates that are being used.  I thought it was a 3.9 issue on my windows machine vs 3.11 on VM, but guess not.  For CWBI, CWBI test always worked, we are working on getting CWBI-prod updated once that is done I will test that one as well.
