### ISSUE TITLE
Add filters on Catalog API  GET request

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#85]
The time series ID filter is the most important. Location category and group as well as Time Series category and group filters would be secondary.

**Comment by adamkorynta** [comment]
Similarly for /catalog/locations, filtering based on locationId is necessary. Filtering on categoryId and groupId are secondary.

**Comment by rripken** [comment]
I've added regexp_like filters for id, category and group to the Timeseries and Location catalog endpoint. 
#102

**Comment by adamkorynta** [comment]
It looks like the category and group are for locations only. Additional parameterization of timeseries categories and groups are utilized in the CAVI.

**Comment by adamkorynta** [comment]
Also using the filters causes duplicate entries to show up in the returned catalog.
