### ISSUE TITLE
timeseries delete - ability to delete entire timeseries

### ISSUE THREAD

**Issue by Enovotny** [USACE/cwms-data-api#852]
the timeseries delete endpoint appears to only have the ability to delete data in the timeseries.  Should it also have the ability to delete the entire time series and include the method of DELETE_ALL, DELETE_KEY, DELETE_DATA.  This also appears to be the case for Text time series.  I am not sure if this was a decision that was made or not.  

mostly wanted to use this for testing purposes being able to clean up after I test out functions.  Can't delete test locations until timeseries are removed.  I can see the why if this was a design decision.

**Comment by MikeNeilson** [comment]
the locations endpoint should have a delete cascade option. So you should only need to delete cascade the location.

Deletion of the actual time series may need to use the time series identifier endpoint. We split up some of that behavior for logic seperation.

**Comment by Enovotny** [comment]
Ah I see.  I don't see the delete cascade option for locations in cwbi-test at the moment only allows the location-id and office-id, but I do see the timeseries identifier.  That helps.  thanks

**Comment by MikeNeilson** [comment]
It's not there on purpose, https://github.com/USACE/cwms-data-api/blob/63181f42bea243d58fe021c348bd52336dbd556a/cwms-data-api/src/main/java/cwms/cda/api/LocationController.java#L386

set `cascade-delete=true` as one of the query parameters.

That'll be added to more formal documentation but we decided to leave it out of swagger as, as the comment says, it's particularly destructive.
