### ISSUE TITLE
Some New Endpoints Return Sensitive Data - Should Require Auth

### ISSUE THREAD

**Issue by krowvin** [USACE/cwms-data-api#871]
The following are endpoints that I tested and that, for some reason or another (REGI?), have IP address/User Information/Hostnames in them. 

Would the best method be to force authentication of these GET requests? 

# Project Lock Rights Endpoint

### Command
```bash
curl -X 'GET' \  'https://T7HOST:TCPORT/swt-data/project-lock-rights?office-mask=SWT' \  -H 'accept: application/json'
```

### Result
Having a user in REGI create a lock, then running that to see the output gives this
```json
[
  {
    "office-id": "SWT",
    "project-id": "ALTU",
    "application-id": "regi;daily ops",
    "acquire-time": 1725640446000,
    "session-user": "<USERNAME REDACTED>",
    "os-user": "<USERNAME REDACTED>",
    "session-program": "JDBC Thin Client",
    "session-machine": "<SYSTEM HOSTNAME REDACTED>"
  }
]
```

# Project Lock Revoker Rights Endpoint
### Command
```bash
curl -X 'GET' \
  'https://T7HOST:TCPORT/swt-data/project-lock-rights?office-mask=SWT' \
  -H 'accept: application/json'
  ```
  ### Result
  ```json
  [
  {
    "office-id": "SWT",
    "project-id": "BIGH",
    "application-id": "regi",
    "user-id": "<REDACTED USERID 1>"
  },
  {
    "office-id": "SWT",
    "project-id": "WAUR",
    "application-id": "regi",
    "user-id": "<REDACTED USERID 2>"
  },
  ...
  ]
  ```

**Comment by rma-rripken** [comment]
https://github.com/USACE/cwms-data-api/pull/872

Its possible there is still a place or two. I'm checking

**Comment by rma-rripken** [comment]
oh, right.  the IT will need the auth added too

**Comment by rma-psmorris** [comment]
Auth added by Ryan to this endpoint. Other concerns as follows:
Future addition of the MQ pieces might have sensitive data.
Get endpoints to properties, CLOB, and BLOB could have auth added given their usage to store application level data. @MikeNeilson do you have thoughts here?

**Comment by MikeNeilson** [comment]
MQ would be authorized only; unless a compelling argument is made otherwise. But even then the scope of data would be limited.

CLOB/BLOB. fair point. Will require further consideration.

**Comment by MikeNeilson** [comment]
Though it dawns on me that properties, and probably water supply, and honestly most of the "REGI" derived endpoints *should* be authorized even for read. Charles also found some hostnames in the properties that we assume were stored by REGI, but it also makes sense that that particular properties endpoint isn't for public consumption.

**Comment by adamkorynta** [comment]
Project lock endpoints and properties were merged under the attached PR's. Closing this issue.
