### ISSUE TITLE
timeseries/recent end point returns Empty Response

### ISSUE THREAD

**Issue by JeremyDKellett** [USACE/cwms-data-api#874]
Hi everyone, 

I'm trying to get the timeseries/recent end point to work with NAE data and am experiencing an Empty Response:

To replicate:

https://cwms-data-test.cwbi.us/cwms-data/timeseries/recent?office=NAE&category-id=NAE%20Data%20Dissemination&group-id=Project%20Status&unit-system=EN

The end point is timing out and/or returning and Empty Response:
![image](https://github.com/user-attachments/assets/f518ad7f-e468-4b9f-bb16-962624348112)
Any suggestions are appreciated!

**Comment by MikeNeilson** [comment]
Doing a quick test now, but most like it's just a performance issue. I suspect that particular group isn't exactly small.

**Comment by MikeNeilson** [comment]
Apparently it's a little bit of both:
```
java.lang.IllegalArgumentException: Field ("CWMS_20"."AV_TSV_DQU"."CWMS_TS_ID") is not contained in Row (
  "alias_4087323"."OFFICE_ID",
  "alias_4087323"."TS_CODE",
  "alias_4087323"."VERSION_DATE",
  "alias_4087323"."DATA_ENTRY_DATE",
  "alias_4087323"."VALUE",
  "alias_4087323"."QUALITY_CODE",
  "alias_4087323"."START_DATE",
  "alias_4087323"."END_DATE",
  "alias_4087323"."DATE_TIME",
  "alias_4087323"."UNIT_ID",
  "alias_4087323"."TS_ID",
  "alias_4087323"."ATTRIBUTE"
)
                at org.jooq.impl.Tools.indexFail(Tools.java:2144)
                at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:333)
                at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1282)
                at cwms.cda.data.dao.TimeSeriesDaoImpl.buildTsvDqu(TimeSeriesDaoImpl.java:977)
```

**Comment by rma-rripken** [comment]
@zach-rma #885 probably fixed this and it can be closed - right?

**Comment by zack-rma** [comment]
Yes, I'll close it
