### ISSUE TITLE
504 Gateway Time-out on API

### ISSUE THREAD

**Issue by gamiller0-tva** [USACE/cwms-data-api#932]
Looks like the API has been down for the last hour or so.

**Comment by MikeNeilson** [comment]
Looking into it now, thanks for letting us know.

**Comment by MikeNeilson** [comment]
Something with the host, our IT dept has been informed. No eta yet.

**Comment by MikeNeilson** [comment]
It's back up. It was a larger issue than just the site so if you're still seeing gaps in the actual data it should fill in. If it hasn't by a few hours, let us know.

**Comment by gamiller0-tva** [comment]
Thanks!
