### ISSUE TITLE
Need time series code (ts_code) endpoint

### ISSUE THREAD

**Issue by inguyen314** [USACE/cwms-data-api#964]
I need ts_code for a time series. 

I have an existing application that utilized the local schema table. This table uses ts_code instead of time series id (name).

**Comment by MikeNeilson** [comment]
Okay, so this one is a hard no. Exposing the ts_code fundamentally against the API philosophy and will make any future horizontal scaling difficult. There are additional reasons, but unless asked specifically I don't want to drown you in the details in this ticket.

CDA will not expose *any* of the _code fields to 

You should modify your application to use the time series name. The Office+Name, of any data, not just time series, is the "canonical name." The _code field is an internal detail.

If that application is SQL and in the database, the solution is to review the code and determine either a replacement, or the process to integrated such code into the database installation and then CDA.

For additional information, or do just try and make your case see: https://github.com/USACE/cwms-data-api/discussions/942

And the wiki: https://github.com/USACE/cwms-data-api/wiki/API-Design (specifically in Design Philosphy the line "do no expose surrogate keys."

**Comment by inguyen314** [comment]
thank you Mike

**Comment by inguyen314** [comment]
I was able to get the ts_code with this endpoint. 

https://wm.mvs.ds.usace.army.mil:8243/mvs-data/timeseries/group/Stage?office=MVS&category-id=Commerce-Mississippi


```
{
  "office-id": "MVS",
  "id": "Stage",
  "time-series-category": {
    "office-id": "MVS",
    "id": "Commerce-Mississippi"
  },
  "assigned-time-series": [
    {
      "office-id": "MVS",
      "timeseries-id": "Commerce-Mississippi.Stage.Inst.30Minutes.0.lrgsShef-rev",
      "ts-code": 4182018
    }
  ]
}
```

**Comment by MikeNeilson** [comment]
That is a bug, that is sadly not fixed in the latest version. Thanks for letting us know.
