### ISSUE TITLE
Add support for time series extents

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#97]
CWMSVue utilities the following query to obtain the time window extents for the time range columns in the time series tab.

```
SELECT cwms_v_ts_extents_utc.db_office_id,
       cwms_v_ts_extents_utc.ts_id,
       cwms_v_ts_id.interval_utc_offset,
       cwms_v_loc.time_zone_name,
       cwms_v_ts_extents_utc.earliest_time,
       cwms_v_ts_extents_utc.latest_time
FROM cwms_v_ts_extents_utc
         INNER JOIN cwms_v_loc ON cwms_v_ts_extents_utc.location_id = cwms_v_loc.location_id AND
                                  cwms_v_ts_extents_utc.db_office_id = cwms_v_loc.db_office_id
         INNER JOIN cwms_v_ts_id ON cwms_v_ts_extents_utc.ts_id = cwms_v_ts_id.cwms_ts_id AND
                                    cwms_v_ts_extents_utc.db_office_id = cwms_v_ts_id.db_office_id
WHERE UPPER(cwms_v_ts_extents_utc.ts_id) LIKE UPPER(NVL(cwms_util.normalize_wildcards(TRIM(?)), '%'))
  AND UPPER(cwms_v_ts_extents_utc.db_office_id) LIKE UPPER(NVL(cwms_util.normalize_wildcards(TRIM(?)), '%'))
```

**Comment by MikeNeilson** [comment]
Do you need that in the catalog or the actual timeseries retrieval?

**Comment by adamkorynta** [comment]
Either as part of the catalog request or a separate /timeseries/extents endpoint.

**Comment by MikeNeilson** [comment]
Hmm. A new endpoint isn't difficult to add, do we think it would be queried specifically very often?

**Comment by adamkorynta** [comment]
I'd prefer it was added to the time series catalog return given our current usage is coupled. Once https://github.com/USACE/cwms-radar-api/issues/85 is implemented, it would solve the API call for extents on a single ID.

**Comment by MikeNeilson** [comment]
okay.

**Comment by adamkorynta** [comment]
Looks good! Client API merged in: https://github.com/HydrologicEngineeringCenter/cwms-radar-client/pull/4
