### ISSUE TITLE
Writing timeseries data via CDA

### ISSUE THREAD

**Issue by michaelstanfill** [USACE/cwms-data-api#973]
I've run into a puzzling error trying to write timeseries data via CDA.  With the latest release (3.15 RC 15), I'm trying to modify a single value, but keep receiving a `500` error:
```json
{
  "message": "Formatting error:Could not deserialize: [org.apache.catalina.connector.CoyoteInputStream@17316d06](mailto:org.apache.catalina.connector.CoyoteInputStream@17316d06) of type: class cwms.cda.data.dto.TimeSeries",
  "incidentIdentifier": "1305795948658333263",
  "details": {}
}
```
The POST I'm making is:
```python
r = requests.Session().post(
      't7-tomcat:port/nwdp-data-315RC15/timeseries',
      headers={        'accept': '*/*',
                'Authorization': 'apikey ' + api_key,
                 'Content-Type': 'application/json;version=2' },
       params={      'create-as-lrts': False,
                'override-protection': True,
                         'store-rule': 'REPLACE ALL' },
         data={   'name': 'ABDW.Precip-Inc.Total.1Day.1Day.RFC-RAW',
             'office-id': 'NWDP',
                 'units': 'in',
                'values': [ [ 1733745600000, 1.0, 0 ] ] },
       verify=False )
```
Sadly, the `tomcat` logs do not appear to be available to look up the `incidentIdentifier`.

**Comment by krowvin** [comment]
I looked over what cwms-python does for`store_timeseries` and one thing I did notice is that if the data type is a dictionary they are casting it to a string with `json.dumps(data)`:

- https://github.com/HydrologicEngineeringCenter/cwms-python/blob/main/cwms/api.py#L312

~I also recommend copying the headers he has two lines above on 310 if that change does not help.~ Nevermind! They look to be the same.


How I got to that conclusion was going backwards from the store_timeseries call:

store_timeseries: 
- https://github.com/HydrologicEngineeringCenter/cwms-python/blob/main/cwms/timeseries/timeseries.py#L295

api.post()
- https://github.com/HydrologicEngineeringCenter/cwms-python/blob/main/cwms/api.py#L284


The proposed updated code would be

```python
import json
r = requests.Session().post(
      'T7-tomcat:port/nwdp-data-315RC15/timeseries',
      headers={        'accept': '*/*',
                'Authorization': 'apikey ' + api_key,
                 'Content-Type': 'application/json;version=2' },
       params={      'create-as-lrts': False,
                'override-protection': True,
                         'store-rule': 'REPLACE ALL' },
         data=json.dumps(
         {   'name': 'ABDW.Precip-Inc.Total.1Day.1Day.RFC-RAW',
             'office-id': 'NWDP',
                 'units': 'in',
                'values': [ [ 1733745600000, 1.0, 0 ] ] },
       verify=False )
       )
```
Let me know if this does not solve it for you! As for the Logs, please also let me know if you are unable to get those updating again.

**Comment by michaelstanfill** [comment]
Yep, that was it.  In retrospect, specifying the `Content-Type` was a clue, but I missed that the `POST` data had to be JSON encoded _prior_ to passing it.  Incidentally, this technique of bypassing URL-encoding appears to have become common enough that later versions of `requests` provide for it by allowing you to replace `data=` with `json=`, which will JSON-encode your data structure and set `Content-Type=application/json`.  The `;version=2` clarification doesn't seem to be necessary here, and may just be there from force of habit.  The following abbreviated call works just fine:
```python
r = requests.post(
      'https://t7-tomcat:port/nwdp-data-315RC15/timeseries',
      headers={   'Authorization': 'apikey ' + api_key },
       params={ 'override-protection': True,
                         'store-rule': 'REPLACE ALL' },
         json={   'name': 'ABDW.Precip-Inc.Total.1Day.1Day.RFC-RAW',
             'office-id': 'NWDP',
                 'units': 'in',
                'values': [ [ 1733745600000, 1.0, 0 ] ] },
       verify=False )
```
