### ISSUE TITLE
https://cwms-data.usace.army.mil/cwms-data currently offline. Backup URL in responses.

### ISSUE THREAD

**Issue by gamiller0-tva** [USACE/cwms-data-api#997]
I'm getting an error that says "Failed to load API definition" when trying to go to the swagger page.  

We haven't been getting data in for a few days via the API.  I was also trying to run some old queries an "HTTP Status 404 – Not Found"

**Comment by MikeNeilson** [comment]
Use https://cwms.sec.usace.army.mil/cwms-data

We had a password expire on us and working to get it update. Eventually the current URL will just point to the above so no need to permanently change the URL but it will have the same data.

**Comment by gamiller0-tva** [comment]
Thanks! Good to have the backup URL.

**Comment by MikeNeilson** [comment]
The original URL is now active again.
